/*
Copyright 2015-2026 Gravitational, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: optional.proto

package optional

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	github_com_hashicorp_terraform_plugin_framework_attr "github.com/hashicorp/terraform-plugin-framework/attr"
	github_com_hashicorp_terraform_plugin_framework_datasource_schema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	github_com_hashicorp_terraform_plugin_framework_diag "github.com/hashicorp/terraform-plugin-framework/diag"
	github_com_hashicorp_terraform_plugin_framework_resource_schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	github_com_hashicorp_terraform_plugin_framework_types "github.com/hashicorp/terraform-plugin-framework/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// GenSchemaOptionalTestResource returns Terraform Framework resource schema definition for OptionalTest
func GenSchemaOptionalTestResource(ctx context.Context) (github_com_hashicorp_terraform_plugin_framework_resource_schema.Schema, github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics) {
	return github_com_hashicorp_terraform_plugin_framework_resource_schema.Schema{Attributes: map[string]github_com_hashicorp_terraform_plugin_framework_resource_schema.Attribute{
		"choice_a": github_com_hashicorp_terraform_plugin_framework_resource_schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"choice_b": github_com_hashicorp_terraform_plugin_framework_resource_schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"optional_bool": github_com_hashicorp_terraform_plugin_framework_resource_schema.BoolAttribute{
			Description: "OptionalBool is a proto3 optional bool field",
			Optional:    true,
		},
		"optional_inner_message": github_com_hashicorp_terraform_plugin_framework_resource_schema.SingleNestedAttribute{
			Attributes: map[string]github_com_hashicorp_terraform_plugin_framework_resource_schema.Attribute{"inner_bool": github_com_hashicorp_terraform_plugin_framework_resource_schema.BoolAttribute{
				Description: "",
				Optional:    true,
			}},
			Description: "OptionalInnerMessage is a proto3 optional message field",
			Optional:    true,
		},
		"optional_int64": github_com_hashicorp_terraform_plugin_framework_resource_schema.Int64Attribute{
			Description: "OptionalInt64 is a proto3 optional int64 field",
			Optional:    true,
		},
		"optional_map": github_com_hashicorp_terraform_plugin_framework_resource_schema.MapAttribute{
			Computed:    true,
			Description: "maps don't support optional keyword, but we add it here to check the generation",
			ElementType: github_com_hashicorp_terraform_plugin_framework_types.StringType,
			Optional:    true,
		},
		"optional_str": github_com_hashicorp_terraform_plugin_framework_resource_schema.StringAttribute{
			Description: "OptionalStr is a proto3 optional string field",
			Optional:    true,
		},
		"string_list": github_com_hashicorp_terraform_plugin_framework_resource_schema.ListAttribute{
			Computed:    true,
			Description: "lists don't support the optional keyword, but we add it here to check the generation",
			ElementType: github_com_hashicorp_terraform_plugin_framework_types.StringType,
			Optional:    true,
		},
	}}, nil
}

// GenSchemaOptionalTestDataSource returns Terraform Framework datasource schema definition for OptionalTest
func GenSchemaOptionalTestDataSource(ctx context.Context) (github_com_hashicorp_terraform_plugin_framework_datasource_schema.Schema, github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics) {
	return github_com_hashicorp_terraform_plugin_framework_datasource_schema.Schema{Attributes: map[string]github_com_hashicorp_terraform_plugin_framework_datasource_schema.Attribute{
		"choice_a": github_com_hashicorp_terraform_plugin_framework_datasource_schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"choice_b": github_com_hashicorp_terraform_plugin_framework_datasource_schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"optional_bool": github_com_hashicorp_terraform_plugin_framework_datasource_schema.BoolAttribute{
			Description: "OptionalBool is a proto3 optional bool field",
			Optional:    true,
		},
		"optional_inner_message": github_com_hashicorp_terraform_plugin_framework_datasource_schema.SingleNestedAttribute{
			Attributes: map[string]github_com_hashicorp_terraform_plugin_framework_datasource_schema.Attribute{"inner_bool": github_com_hashicorp_terraform_plugin_framework_datasource_schema.BoolAttribute{
				Description: "",
				Optional:    true,
			}},
			Description: "OptionalInnerMessage is a proto3 optional message field",
			Optional:    true,
		},
		"optional_int64": github_com_hashicorp_terraform_plugin_framework_datasource_schema.Int64Attribute{
			Description: "OptionalInt64 is a proto3 optional int64 field",
			Optional:    true,
		},
		"optional_map": github_com_hashicorp_terraform_plugin_framework_datasource_schema.MapAttribute{
			Computed:    true,
			Description: "maps don't support optional keyword, but we add it here to check the generation",
			ElementType: github_com_hashicorp_terraform_plugin_framework_types.StringType,
			Optional:    true,
		},
		"optional_str": github_com_hashicorp_terraform_plugin_framework_datasource_schema.StringAttribute{
			Description: "OptionalStr is a proto3 optional string field",
			Optional:    true,
		},
		"string_list": github_com_hashicorp_terraform_plugin_framework_datasource_schema.ListAttribute{
			Computed:    true,
			Description: "lists don't support the optional keyword, but we add it here to check the generation",
			ElementType: github_com_hashicorp_terraform_plugin_framework_types.StringType,
			Optional:    true,
		},
	}}, nil
}

// CopyOptionalTestFromTerraform copies contents of the source Terraform object into a target struct
func CopyOptionalTestFromTerraform(_ context.Context, tf github_com_hashicorp_terraform_plugin_framework_types.Object, obj *OptionalTest) github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics {
	var diags github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics
	obj.RealOneOf = nil
	{
		a, ok := tf.Attributes()["choice_a"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.choice_a"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.choice_a", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.IsNull() && !v.IsUnknown() {
					t = (v.ValueString())
				}
				if !v.IsNull() && !v.IsUnknown() {
					obj.RealOneOf = &OptionalTest_ChoiceA{ChoiceA: t}
				}
			}
		}
	}
	{
		a, ok := tf.Attributes()["choice_b"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.choice_b"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.choice_b", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.IsNull() && !v.IsUnknown() {
					t = (v.ValueString())
				}
				if !v.IsNull() && !v.IsUnknown() {
					obj.RealOneOf = &OptionalTest_ChoiceB{ChoiceB: t}
				}
			}
		}
	}
	{
		a, ok := tf.Attributes()["optional_bool"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.optional_bool"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Bool)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.optional_bool", "github.com/hashicorp/terraform-plugin-framework/types.Bool"})
			} else {
				var t *bool
				if !v.IsNull() && !v.IsUnknown() {
					c := (v.ValueBool())
					t = &c
				}
				obj.OptionalBool = t
			}
		}
	}
	{
		a, ok := tf.Attributes()["optional_inner_message"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.optional_inner_message"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Object)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.optional_inner_message", "github.com/hashicorp/terraform-plugin-framework/types.Object"})
			} else {
				obj.OptionalInnerMessage = nil
				if !v.IsNull() && !v.IsUnknown() {
					tf := v
					obj.OptionalInnerMessage = &InnerMessage{}
					obj := obj.OptionalInnerMessage
					{
						a, ok := tf.Attributes()["inner_bool"]
						if !ok {
							diags.Append(attrReadMissingDiag{"OptionalTest.optional_inner_message.inner_bool"})
						} else {
							v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Bool)
							if !ok {
								diags.Append(attrReadConversionFailureDiag{"OptionalTest.optional_inner_message.inner_bool", "github.com/hashicorp/terraform-plugin-framework/types.Bool"})
							} else {
								var t *bool
								if !v.IsNull() && !v.IsUnknown() {
									c := (v.ValueBool())
									t = &c
								}
								obj.InnerBool = t
							}
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attributes()["optional_int64"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.optional_int64"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.optional_int64", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
			} else {
				var t *int64
				if !v.IsNull() && !v.IsUnknown() {
					c := (v.ValueInt64())
					t = &c
				}
				obj.OptionalInt64 = t
			}
		}
	}
	{
		a, ok := tf.Attributes()["optional_map"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.optional_map"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Map)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.optional_map", "github.com/hashicorp/terraform-plugin-framework/types.Map"})
			} else {
				obj.OptionalMap = make(map[string]string, len(v.Elements()))
				if !v.IsNull() && !v.IsUnknown() {
					for k, a := range v.Elements() {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"OptionalTest.optional_map", "github_com_hashicorp_terraform_plugin_framework_types.String"})
						} else {
							var t string
							if !v.IsNull() && !v.IsUnknown() {
								t = (v.ValueString())
							}
							obj.OptionalMap[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attributes()["optional_str"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.optional_str"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.optional_str", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t *string
				if !v.IsNull() && !v.IsUnknown() {
					c := (v.ValueString())
					t = &c
				}
				obj.OptionalStr = t
			}
		}
	}
	{
		a, ok := tf.Attributes()["string_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.string_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.string_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.StringList = make([]string, len(v.Elements()))
				if !v.IsNull() && !v.IsUnknown() {
					for k, a := range v.Elements() {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"OptionalTest.string_list", "github_com_hashicorp_terraform_plugin_framework_types.String"})
						} else {
							var t string
							if !v.IsNull() && !v.IsUnknown() {
								t = (v.ValueString())
							}
							obj.StringList[k] = t
						}
					}
				}
			}
		}
	}
	return diags
}

// CopyOptionalTestToTerraform copies contents of source struct into a Terraform object.
func CopyOptionalTestToTerraform(ctx context.Context, obj *OptionalTest, tf *github_com_hashicorp_terraform_plugin_framework_types.Object) (github_com_hashicorp_terraform_plugin_framework_types.Object, github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics) {
	return CopyOptionalTestToTerraformPreserveUnknown(ctx, obj, tf, false)
}

// CopyOptionalTestToTerraformPreserveUnknown copies contents of source struct into a Terraform object.
// Set preserveUnknown to true to preserve unknown values.
func CopyOptionalTestToTerraformPreserveUnknown(ctx context.Context, obj *OptionalTest, tf *github_com_hashicorp_terraform_plugin_framework_types.Object, preserveUnknown bool) (github_com_hashicorp_terraform_plugin_framework_types.Object, github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics) {
	schema, diags := GenSchemaOptionalTestResource(ctx)
	if diags.HasError() {
		return github_com_hashicorp_terraform_plugin_framework_types.Object{}, diags
	}
	attrType := schema.Type().(github_com_hashicorp_terraform_plugin_framework_types.ObjectType)
	var attrs map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value
	if tf == nil || tf.Attributes() == nil {
		attrs = make(map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value)
	} else {
		attrs = tf.Attributes()
	}
	{
		var v github_com_hashicorp_terraform_plugin_framework_attr.Value
		existing := attrs["choice_a"]
		if preserveUnknown && existing != nil && existing.IsUnknown() {
			v = github_com_hashicorp_terraform_plugin_framework_types.StringUnknown()
		} else {
			{
				obj, ok := obj.RealOneOf.(*OptionalTest_ChoiceA)
				if !ok {
					v = github_com_hashicorp_terraform_plugin_framework_types.StringNull()
				} else {
					v = github_com_hashicorp_terraform_plugin_framework_types.StringValue(string(obj.ChoiceA))
				}
			}
		}
		attrs["choice_a"] = v
	}
	{
		var v github_com_hashicorp_terraform_plugin_framework_attr.Value
		existing := attrs["choice_b"]
		if preserveUnknown && existing != nil && existing.IsUnknown() {
			v = github_com_hashicorp_terraform_plugin_framework_types.StringUnknown()
		} else {
			{
				obj, ok := obj.RealOneOf.(*OptionalTest_ChoiceB)
				if !ok {
					v = github_com_hashicorp_terraform_plugin_framework_types.StringNull()
				} else {
					v = github_com_hashicorp_terraform_plugin_framework_types.StringValue(string(obj.ChoiceB))
				}
			}
		}
		attrs["choice_b"] = v
	}
	{
		var v github_com_hashicorp_terraform_plugin_framework_attr.Value
		existing := attrs["optional_bool"]
		if preserveUnknown && existing != nil && existing.IsUnknown() {
			v = github_com_hashicorp_terraform_plugin_framework_types.BoolUnknown()
		} else {
			if obj.OptionalBool == nil {
				v = github_com_hashicorp_terraform_plugin_framework_types.BoolNull()
			} else {
				v = github_com_hashicorp_terraform_plugin_framework_types.BoolValue(bool(*obj.OptionalBool))
			}
		}
		attrs["optional_bool"] = v
	}
	{
		attrType, ok := attrType.AttributeTypes()["optional_inner_message"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"OptionalTest.optional_inner_message"})
		} else {
			attrType, ok := attrType.(github_com_hashicorp_terraform_plugin_framework_types.ObjectType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"OptionalTest.optional_inner_message", "github.com/hashicorp/terraform-plugin-framework/types.ObjectType"})
			} else {
				existing := attrs["optional_inner_message"]
				v := func() github_com_hashicorp_terraform_plugin_framework_attr.Value {
					if preserveUnknown && existing != nil && existing.IsUnknown() {
						return github_com_hashicorp_terraform_plugin_framework_types.ObjectUnknown(attrType.AttributeTypes())
					} else {
						if obj.OptionalInnerMessage == nil {
							return github_com_hashicorp_terraform_plugin_framework_types.ObjectNull(attrType.AttributeTypes())
						} else {
							obj := obj.OptionalInnerMessage
							attrs := make(map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(attrType.AttributeTypes()))
							v, ok := existing.(github_com_hashicorp_terraform_plugin_framework_types.Object)
							if ok && v.Attributes() != nil {
								attrs = v.Attributes()
							}
							{
								var v github_com_hashicorp_terraform_plugin_framework_attr.Value
								existing := attrs["inner_bool"]
								if preserveUnknown && existing != nil && existing.IsUnknown() {
									v = github_com_hashicorp_terraform_plugin_framework_types.BoolUnknown()
								} else {
									if obj.InnerBool == nil {
										v = github_com_hashicorp_terraform_plugin_framework_types.BoolNull()
									} else {
										v = github_com_hashicorp_terraform_plugin_framework_types.BoolValue(bool(*obj.InnerBool))
									}
								}
								attrs["inner_bool"] = v
							}
							result, resultDiags := github_com_hashicorp_terraform_plugin_framework_types.ObjectValue(attrType.AttributeTypes(), attrs)
							diags.Append(resultDiags...)
							return result
						}
					}
				}()
				attrs["optional_inner_message"] = v
			}
		}
	}
	{
		var v github_com_hashicorp_terraform_plugin_framework_attr.Value
		existing := attrs["optional_int64"]
		if preserveUnknown && existing != nil && existing.IsUnknown() {
			v = github_com_hashicorp_terraform_plugin_framework_types.Int64Unknown()
		} else {
			if obj.OptionalInt64 == nil {
				v = github_com_hashicorp_terraform_plugin_framework_types.Int64Null()
			} else {
				v = github_com_hashicorp_terraform_plugin_framework_types.Int64Value(int64(*obj.OptionalInt64))
			}
		}
		attrs["optional_int64"] = v
	}
	{
		attrType, ok := attrType.AttributeTypes()["optional_map"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"OptionalTest.optional_map"})
		} else {
			attrType, ok := attrType.(github_com_hashicorp_terraform_plugin_framework_types.MapType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"OptionalTest.optional_map", "github.com/hashicorp/terraform-plugin-framework/types.MapType"})
			} else {
				var v github_com_hashicorp_terraform_plugin_framework_attr.Value
				existing := attrs["optional_map"]
				if preserveUnknown && existing != nil && existing.IsUnknown() {
					v = github_com_hashicorp_terraform_plugin_framework_types.MapUnknown(attrType.ElementType())
				} else {
					oldElems := make(map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.OptionalMap))
					c, ok := existing.(github_com_hashicorp_terraform_plugin_framework_types.Map)
					if ok && c.Elements() != nil {
						oldElems = c.Elements()
					}
					elems := make(map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.OptionalMap))
					for k, a := range obj.OptionalMap {
						var v github_com_hashicorp_terraform_plugin_framework_attr.Value
						existing := oldElems[k]
						if preserveUnknown && existing != nil && existing.IsUnknown() {
							v = github_com_hashicorp_terraform_plugin_framework_types.StringUnknown()
						} else {
							v = github_com_hashicorp_terraform_plugin_framework_types.StringValue(string(a))
						}
						elems[k] = v
					}
					result, resultDiags := github_com_hashicorp_terraform_plugin_framework_types.MapValue(attrType.ElementType(), elems)
					diags.Append(resultDiags...)
					v = result
				}
				attrs["optional_map"] = v
			}
		}
	}
	{
		var v github_com_hashicorp_terraform_plugin_framework_attr.Value
		existing := attrs["optional_str"]
		if preserveUnknown && existing != nil && existing.IsUnknown() {
			v = github_com_hashicorp_terraform_plugin_framework_types.StringUnknown()
		} else {
			if obj.OptionalStr == nil {
				v = github_com_hashicorp_terraform_plugin_framework_types.StringNull()
			} else {
				v = github_com_hashicorp_terraform_plugin_framework_types.StringValue(string(*obj.OptionalStr))
			}
		}
		attrs["optional_str"] = v
	}
	{
		attrType, ok := attrType.AttributeTypes()["string_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"OptionalTest.string_list"})
		} else {
			attrType, ok := attrType.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"OptionalTest.string_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				var v github_com_hashicorp_terraform_plugin_framework_attr.Value
				existing := attrs["string_list"]
				if preserveUnknown && existing != nil && existing.IsUnknown() {
					v = github_com_hashicorp_terraform_plugin_framework_types.ListUnknown(attrType.ElementType())
				} else {
					oldElems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.StringList))
					c, ok := existing.(github_com_hashicorp_terraform_plugin_framework_types.List)
					if ok && c.Elements() != nil {
						oldElems = c.Elements()
					}
					elems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.StringList))
					copy(elems, oldElems)
					for k, a := range obj.StringList {
						var v github_com_hashicorp_terraform_plugin_framework_attr.Value
						existing := elems[k]
						if preserveUnknown && existing != nil && existing.IsUnknown() {
							v = github_com_hashicorp_terraform_plugin_framework_types.StringUnknown()
						} else {
							v = github_com_hashicorp_terraform_plugin_framework_types.StringValue(string(a))
						}
						elems[k] = v
					}
					result, resultDiags := github_com_hashicorp_terraform_plugin_framework_types.ListValue(attrType.ElementType(), elems)
					diags.Append(resultDiags...)
					v = result
				}
				attrs["string_list"] = v
			}
		}
	}
	result, resultDiags := github_com_hashicorp_terraform_plugin_framework_types.ObjectValue(attrType.AttributeTypes(), attrs)
	diags.Append(resultDiags...)
	return result, diags
}

// attrReadMissingDiag represents diagnostic message on an attribute missing in the source object
type attrReadMissingDiag struct {
	Path string
}

func (d attrReadMissingDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrReadMissingDiag) Summary() string {
	return "Error reading from Terraform object"
}

func (d attrReadMissingDiag) Detail() string {
	return fmt.Sprintf("A value for %v is missing in the source Terraform object Attributes", d.Path)
}

func (d attrReadMissingDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrReadConversionFailureDiag represents diagnostic message on a failed type conversion on read
type attrReadConversionFailureDiag struct {
	Path string
	Type string
}

func (d attrReadConversionFailureDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrReadConversionFailureDiag) Summary() string {
	return "Error reading from Terraform object"
}

func (d attrReadConversionFailureDiag) Detail() string {
	return fmt.Sprintf("A value for %v can not be converted to %v", d.Path, d.Type)
}

func (d attrReadConversionFailureDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteMissingDiag represents diagnostic message on an attribute missing in the target object
type attrWriteMissingDiag struct {
	Path string
}

func (d attrWriteMissingDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteMissingDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteMissingDiag) Detail() string {
	return fmt.Sprintf("A value for %v is missing in the source Terraform object AttributeTypes", d.Path)
}

func (d attrWriteMissingDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteConversionFailureDiag represents diagnostic message on a failed type conversion on write
type attrWriteConversionFailureDiag struct {
	Path string
	Type string
}

func (d attrWriteConversionFailureDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteConversionFailureDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteConversionFailureDiag) Detail() string {
	return fmt.Sprintf("A value for %v can not be converted to %v", d.Path, d.Type)
}

func (d attrWriteConversionFailureDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteGeneralError represents diagnostic message on a generic error on write
type attrWriteGeneralError struct {
	Path string
	Err  error
}

func (d attrWriteGeneralError) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteGeneralError) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteGeneralError) Detail() string {
	return fmt.Sprintf("%s: %s", d.Path, d.Err.Error())
}

func (d attrWriteGeneralError) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteUnexpectedExistingTypeDiag represents diagnostic message when a field is initialized with a value whose go
// type does not match what we'd expect.
type attrWriteUnexpectedExistingTypeDiag struct {
	Path string
	Type string
}

func (d attrWriteUnexpectedExistingTypeDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteUnexpectedExistingTypeDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteUnexpectedExistingTypeDiag) Detail() string {
	return fmt.Sprintf("A value for %v is already initialized and its type is not %v", d.Path, d.Type)
}

func (d attrWriteUnexpectedExistingTypeDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}
