/*
Copyright 2015-2026 Gravitational, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: optional.proto

package optional

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	github_com_hashicorp_terraform_plugin_framework_attr "github.com/hashicorp/terraform-plugin-framework/attr"
	github_com_hashicorp_terraform_plugin_framework_diag "github.com/hashicorp/terraform-plugin-framework/diag"
	github_com_hashicorp_terraform_plugin_framework_tfsdk "github.com/hashicorp/terraform-plugin-framework/tfsdk"
	github_com_hashicorp_terraform_plugin_framework_types "github.com/hashicorp/terraform-plugin-framework/types"
	github_com_hashicorp_terraform_plugin_go_tftypes "github.com/hashicorp/terraform-plugin-go/tftypes"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// GenSchemaOptionalTest returns tfsdk.Schema definition for OptionalTest
func GenSchemaOptionalTest(ctx context.Context) (github_com_hashicorp_terraform_plugin_framework_tfsdk.Schema, github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics) {
	return github_com_hashicorp_terraform_plugin_framework_tfsdk.Schema{Attributes: map[string]github_com_hashicorp_terraform_plugin_framework_tfsdk.Attribute{
		"choice_a": {
			Description: "",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
		"choice_b": {
			Description: "",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
		"optional_bool": {
			Description: "OptionalBool is a proto3 optional bool field",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.BoolType,
		},
		"optional_inner_message": {
			Attributes: github_com_hashicorp_terraform_plugin_framework_tfsdk.SingleNestedAttributes(map[string]github_com_hashicorp_terraform_plugin_framework_tfsdk.Attribute{"inner_bool": {
				Description: "",
				Optional:    true,
				Type:        github_com_hashicorp_terraform_plugin_framework_types.BoolType,
			}}),
			Description: "OptionalInnerMessage is a proto3 optional message field",
			Optional:    true,
		},
		"optional_int64": {
			Description: "OptionalInt64 is a proto3 optional int64 field",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.Int64Type,
		},
		"optional_map": {
			Description: "maps don't support optional keyword, but we add it here to check the generation",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.MapType{ElemType: github_com_hashicorp_terraform_plugin_framework_types.StringType},
		},
		"optional_str": {
			Description: "OptionalStr is a proto3 optional string field",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
		"string_list": {
			Description: "lists don't support the optional keyword, but we add it here to check the generation",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.ListType{ElemType: github_com_hashicorp_terraform_plugin_framework_types.StringType},
		},
	}}, nil
}

// CopyOptionalTestFromTerraform copies contents of the source Terraform object into a target struct
func CopyOptionalTestFromTerraform(_ context.Context, tf github_com_hashicorp_terraform_plugin_framework_types.Object, obj *OptionalTest) github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics {
	var diags github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics
	obj.RealOneOf = nil
	{
		a, ok := tf.Attrs["choice_a"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.choice_a"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.choice_a", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.Null && !v.Unknown {
					t = string(v.Value)
				}
				if !v.Null && !v.Unknown {
					obj.RealOneOf = &OptionalTest_ChoiceA{ChoiceA: t}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["choice_b"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.choice_b"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.choice_b", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.Null && !v.Unknown {
					t = string(v.Value)
				}
				if !v.Null && !v.Unknown {
					obj.RealOneOf = &OptionalTest_ChoiceB{ChoiceB: t}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["optional_bool"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.optional_bool"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Bool)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.optional_bool", "github.com/hashicorp/terraform-plugin-framework/types.Bool"})
			} else {
				var t *bool
				if !v.Null && !v.Unknown {
					c := bool(v.Value)
					t = &c
				}
				obj.OptionalBool = t
			}
		}
	}
	{
		a, ok := tf.Attrs["optional_inner_message"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.optional_inner_message"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Object)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.optional_inner_message", "github.com/hashicorp/terraform-plugin-framework/types.Object"})
			} else {
				obj.OptionalInnerMessage = nil
				if !v.Null && !v.Unknown {
					tf := v
					obj.OptionalInnerMessage = &InnerMessage{}
					obj := obj.OptionalInnerMessage
					{
						a, ok := tf.Attrs["inner_bool"]
						if !ok {
							diags.Append(attrReadMissingDiag{"OptionalTest.optional_inner_message.inner_bool"})
						} else {
							v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Bool)
							if !ok {
								diags.Append(attrReadConversionFailureDiag{"OptionalTest.optional_inner_message.inner_bool", "github.com/hashicorp/terraform-plugin-framework/types.Bool"})
							} else {
								var t *bool
								if !v.Null && !v.Unknown {
									c := bool(v.Value)
									t = &c
								}
								obj.InnerBool = t
							}
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["optional_int64"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.optional_int64"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.optional_int64", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
			} else {
				var t *int64
				if !v.Null && !v.Unknown {
					c := int64(v.Value)
					t = &c
				}
				obj.OptionalInt64 = t
			}
		}
	}
	{
		a, ok := tf.Attrs["optional_map"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.optional_map"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Map)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.optional_map", "github.com/hashicorp/terraform-plugin-framework/types.Map"})
			} else {
				obj.OptionalMap = make(map[string]string, len(v.Elems))
				if !v.Null && !v.Unknown {
					for k, a := range v.Elems {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"OptionalTest.optional_map", "github_com_hashicorp_terraform_plugin_framework_types.String"})
						} else {
							var t string
							if !v.Null && !v.Unknown {
								t = string(v.Value)
							}
							obj.OptionalMap[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["optional_str"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.optional_str"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.optional_str", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t *string
				if !v.Null && !v.Unknown {
					c := string(v.Value)
					t = &c
				}
				obj.OptionalStr = t
			}
		}
	}
	{
		a, ok := tf.Attrs["string_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"OptionalTest.string_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"OptionalTest.string_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.StringList = make([]string, len(v.Elems))
				if !v.Null && !v.Unknown {
					for k, a := range v.Elems {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"OptionalTest.string_list", "github_com_hashicorp_terraform_plugin_framework_types.String"})
						} else {
							var t string
							if !v.Null && !v.Unknown {
								t = string(v.Value)
							}
							obj.StringList[k] = t
						}
					}
				}
			}
		}
	}
	return diags
}

// CopyOptionalTestToTerraform copies contents of the source Terraform object into a target struct
func CopyOptionalTestToTerraform(ctx context.Context, obj *OptionalTest, tf *github_com_hashicorp_terraform_plugin_framework_types.Object) github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics {
	var diags github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics
	tf.Null = false
	tf.Unknown = false
	if tf.Attrs == nil {
		tf.Attrs = make(map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value)
	}
	{
		t, ok := tf.AttrTypes["choice_a"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"OptionalTest.choice_a"})
		} else {
			obj, ok := obj.RealOneOf.(*OptionalTest_ChoiceA)
			if !ok {
				obj = &OptionalTest_ChoiceA{}
			}
			v, ok := tf.Attrs["choice_a"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"OptionalTest.choice_a", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"OptionalTest.choice_a", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = string(obj.ChoiceA) == ""
			}
			v.Value = string(obj.ChoiceA)
			v.Unknown = false
			tf.Attrs["choice_a"] = v
		}
	}
	{
		t, ok := tf.AttrTypes["choice_b"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"OptionalTest.choice_b"})
		} else {
			obj, ok := obj.RealOneOf.(*OptionalTest_ChoiceB)
			if !ok {
				obj = &OptionalTest_ChoiceB{}
			}
			v, ok := tf.Attrs["choice_b"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"OptionalTest.choice_b", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"OptionalTest.choice_b", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = string(obj.ChoiceB) == ""
			}
			v.Value = string(obj.ChoiceB)
			v.Unknown = false
			tf.Attrs["choice_b"] = v
		}
	}
	{
		t, ok := tf.AttrTypes["optional_bool"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"OptionalTest.optional_bool"})
		} else {
			v, ok := tf.Attrs["optional_bool"].(github_com_hashicorp_terraform_plugin_framework_types.Bool)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"OptionalTest.optional_bool", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Bool)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"OptionalTest.optional_bool", "github.com/hashicorp/terraform-plugin-framework/types.Bool"})
				}
				v.Null = obj.OptionalBool == nil
			}
			if obj.OptionalBool == nil {
				v.Null = true
			} else {
				v.Null = false
				v.Value = bool(*obj.OptionalBool)
			}
			v.Unknown = false
			tf.Attrs["optional_bool"] = v
		}
	}
	{
		a, ok := tf.AttrTypes["optional_inner_message"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"OptionalTest.optional_inner_message"})
		} else {
			o, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.ObjectType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"OptionalTest.optional_inner_message", "github.com/hashicorp/terraform-plugin-framework/types.ObjectType"})
			} else {
				v, ok := tf.Attrs["optional_inner_message"].(github_com_hashicorp_terraform_plugin_framework_types.Object)
				if !ok {
					v = github_com_hashicorp_terraform_plugin_framework_types.Object{

						AttrTypes: o.AttrTypes,
						Attrs:     make(map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(o.AttrTypes)),
					}
				} else {
					if v.Attrs == nil {
						v.Attrs = make(map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(tf.AttrTypes))
					}
				}
				if obj.OptionalInnerMessage == nil {
					v.Null = true
				} else {
					obj := obj.OptionalInnerMessage
					tf := &v
					{
						t, ok := tf.AttrTypes["inner_bool"]
						if !ok {
							diags.Append(attrWriteMissingDiag{"OptionalTest.optional_inner_message.inner_bool"})
						} else {
							v, ok := tf.Attrs["inner_bool"].(github_com_hashicorp_terraform_plugin_framework_types.Bool)
							if !ok {
								i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
								if err != nil {
									diags.Append(attrWriteGeneralError{"OptionalTest.optional_inner_message.inner_bool", err})
								}
								v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Bool)
								if !ok {
									diags.Append(attrWriteConversionFailureDiag{"OptionalTest.optional_inner_message.inner_bool", "github.com/hashicorp/terraform-plugin-framework/types.Bool"})
								}
								v.Null = obj.InnerBool == nil
							}
							if obj.InnerBool == nil {
								v.Null = true
							} else {
								v.Null = false
								v.Value = bool(*obj.InnerBool)
							}
							v.Unknown = false
							tf.Attrs["inner_bool"] = v
						}
					}
				}
				v.Unknown = false
				tf.Attrs["optional_inner_message"] = v
			}
		}
	}
	{
		t, ok := tf.AttrTypes["optional_int64"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"OptionalTest.optional_int64"})
		} else {
			v, ok := tf.Attrs["optional_int64"].(github_com_hashicorp_terraform_plugin_framework_types.Int64)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"OptionalTest.optional_int64", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"OptionalTest.optional_int64", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
				}
				v.Null = obj.OptionalInt64 == nil
			}
			if obj.OptionalInt64 == nil {
				v.Null = true
			} else {
				v.Null = false
				v.Value = int64(*obj.OptionalInt64)
			}
			v.Unknown = false
			tf.Attrs["optional_int64"] = v
		}
	}
	{
		a, ok := tf.AttrTypes["optional_map"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"OptionalTest.optional_map"})
		} else {
			o, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.MapType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"OptionalTest.optional_map", "github.com/hashicorp/terraform-plugin-framework/types.MapType"})
			} else {
				c, ok := tf.Attrs["optional_map"].(github_com_hashicorp_terraform_plugin_framework_types.Map)
				if !ok {
					c = github_com_hashicorp_terraform_plugin_framework_types.Map{

						ElemType: o.ElemType,
						Elems:    make(map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.OptionalMap)),
						Null:     true,
					}
				} else {
					if c.Elems == nil {
						c.Elems = make(map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.OptionalMap))
					}
				}
				if obj.OptionalMap != nil {
					t := o.ElemType
					for k, a := range obj.OptionalMap {
						v, ok := tf.Attrs["optional_map"].(github_com_hashicorp_terraform_plugin_framework_types.String)
						if !ok {
							i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
							if err != nil {
								diags.Append(attrWriteGeneralError{"OptionalTest.optional_map", err})
							}
							v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
							if !ok {
								diags.Append(attrWriteConversionFailureDiag{"OptionalTest.optional_map", "github.com/hashicorp/terraform-plugin-framework/types.String"})
							}
							v.Null = false
						}
						v.Value = string(a)
						v.Unknown = false
						c.Elems[k] = v
					}
					if len(obj.OptionalMap) > 0 {
						c.Null = false
					}
				}
				c.Unknown = false
				tf.Attrs["optional_map"] = c
			}
		}
	}
	{
		t, ok := tf.AttrTypes["optional_str"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"OptionalTest.optional_str"})
		} else {
			v, ok := tf.Attrs["optional_str"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"OptionalTest.optional_str", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"OptionalTest.optional_str", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = obj.OptionalStr == nil
			}
			if obj.OptionalStr == nil {
				v.Null = true
			} else {
				v.Null = false
				v.Value = string(*obj.OptionalStr)
			}
			v.Unknown = false
			tf.Attrs["optional_str"] = v
		}
	}
	{
		a, ok := tf.AttrTypes["string_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"OptionalTest.string_list"})
		} else {
			o, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"OptionalTest.string_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				c, ok := tf.Attrs["string_list"].(github_com_hashicorp_terraform_plugin_framework_types.List)
				if !ok {
					c = github_com_hashicorp_terraform_plugin_framework_types.List{

						ElemType: o.ElemType,
						Elems:    make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.StringList)),
						Null:     true,
					}
				} else {
					if c.Elems == nil {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.StringList))
					}
				}
				if obj.StringList != nil {
					t := o.ElemType
					if len(obj.StringList) != len(c.Elems) {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.StringList))
					}
					for k, a := range obj.StringList {
						v, ok := tf.Attrs["string_list"].(github_com_hashicorp_terraform_plugin_framework_types.String)
						if !ok {
							i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
							if err != nil {
								diags.Append(attrWriteGeneralError{"OptionalTest.string_list", err})
							}
							v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
							if !ok {
								diags.Append(attrWriteConversionFailureDiag{"OptionalTest.string_list", "github.com/hashicorp/terraform-plugin-framework/types.String"})
							}
							v.Null = string(a) == ""
						}
						v.Value = string(a)
						v.Unknown = false
						c.Elems[k] = v
					}
					if len(obj.StringList) > 0 {
						c.Null = false
					}
				}
				c.Unknown = false
				tf.Attrs["string_list"] = c
			}
		}
	}
	return diags
}

// attrReadMissingDiag represents diagnostic message on an attribute missing in the source object
type attrReadMissingDiag struct {
	Path string
}

func (d attrReadMissingDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrReadMissingDiag) Summary() string {
	return "Error reading from Terraform object"
}

func (d attrReadMissingDiag) Detail() string {
	return fmt.Sprintf("A value for %v is missing in the source Terraform object Attrs", d.Path)
}

func (d attrReadMissingDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrReadConversionFailureDiag represents diagnostic message on a failed type conversion on read
type attrReadConversionFailureDiag struct {
	Path string
	Type string
}

func (d attrReadConversionFailureDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrReadConversionFailureDiag) Summary() string {
	return "Error reading from Terraform object"
}

func (d attrReadConversionFailureDiag) Detail() string {
	return fmt.Sprintf("A value for %v can not be converted to %v", d.Path, d.Type)
}

func (d attrReadConversionFailureDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteMissingDiag represents diagnostic message on an attribute missing in the target object
type attrWriteMissingDiag struct {
	Path string
}

func (d attrWriteMissingDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteMissingDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteMissingDiag) Detail() string {
	return fmt.Sprintf("A value for %v is missing in the source Terraform object AttrTypes", d.Path)
}

func (d attrWriteMissingDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteConversionFailureDiag represents diagnostic message on a failed type conversion on write
type attrWriteConversionFailureDiag struct {
	Path string
	Type string
}

func (d attrWriteConversionFailureDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteConversionFailureDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteConversionFailureDiag) Detail() string {
	return fmt.Sprintf("A value for %v can not be converted to %v", d.Path, d.Type)
}

func (d attrWriteConversionFailureDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteGeneralError represents diagnostic message on a generic error on write
type attrWriteGeneralError struct {
	Path string
	Err  error
}

func (d attrWriteGeneralError) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteGeneralError) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteGeneralError) Detail() string {
	return fmt.Sprintf("%s: %s", d.Path, d.Err.Error())
}

func (d attrWriteGeneralError) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}
