// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test.proto

package test

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Test message definition.
//
// It contains:
//   - elementary fields
//   - repeated elementary fields
//   - maps of elementary fields
//   - other messages (nested)
//   - repeated messages
//   - message maps
//   - custom types
//   - custom duration type
//   - standard google protobuf timestamps
//   - byte arrays, which are treated as strings by default
//
type Test struct {
	// Str string field
	Str string `protobuf:"bytes,1,opt,name=Str,proto3" json:"Str,omitempty"`
	// Int32 int32 field
	Int32 int32 `protobuf:"varint,2,opt,name=Int32,proto3" json:"Int32,omitempty"`
	// Int64 int64 field
	Int64 int64 `protobuf:"varint,3,opt,name=Int64,proto3" json:"Int64,omitempty"`
	// Float float field
	Float float32 `protobuf:"fixed32,4,opt,name=Float,proto3" json:"Float,omitempty"`
	// Double double field
	Double float64 `protobuf:"fixed64,5,opt,name=Double,proto3" json:"Double,omitempty"`
	// Bool bool field
	Bool bool `protobuf:"varint,6,opt,name=Bool,proto3" json:"Bool,omitempty"`
	// Bytest byte[] field
	Bytes []byte `protobuf:"bytes,7,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	// Timestamp time.Time field
	Timestamp time.Time `protobuf:"bytes,8,opt,name=Timestamp,proto3,stdtime" json:"Timestamp"`
	// DurationStd time.Duration field (standard)
	DurationStd time.Duration `protobuf:"varint,9,opt,name=DurationStd,proto3,stdduration" json:"DurationStd,omitempty"`
	// DurationCustom time.Duration field (custom)
	DurationCustom Duration `protobuf:"varint,10,opt,name=DurationCustom,proto3,casttype=Duration" json:"DurationCustom,omitempty"`
	// TimestampN *time.Time field
	TimestampN *time.Time `protobuf:"bytes,11,opt,name=TimestampN,proto3,stdtime" json:"TimestampN,omitempty"`
	// StringA []string field
	StringA []string `protobuf:"bytes,12,rep,name=StringA,proto3" json:"StringA,omitempty"`
	// BoolA []bool field
	BoolA []BoolCustom `protobuf:"varint,13,rep,packed,name=BoolA,proto3,customtype=BoolCustom" json:"BoolA,omitempty"`
	// BytesA [][]byte field
	BytesA [][]byte `protobuf:"bytes,14,rep,name=BytesA,proto3" json:"BytesA,omitempty"`
	// TimestampA []time.Time field
	TimestampA []*time.Time `protobuf:"bytes,15,rep,name=TimestampA,proto3,stdtime" json:"TimestampA,omitempty"`
	// DurationCustomA []time.Duration field
	DurationCustomA []Duration `protobuf:"varint,16,rep,packed,name=DurationCustomA,proto3,casttype=Duration" json:"DurationCustomA,omitempty"`
	// Nested nested message field
	Nested *Nested `protobuf:"bytes,17,opt,name=Nested,proto3" json:"Nested,omitempty"`
	// NestedA nested message array
	NestedA []*Nested `protobuf:"bytes,18,rep,name=NestedA,proto3" json:"NestedA,omitempty"`
	// NestedM normal map
	NestedM map[string]string `protobuf:"bytes,19,rep,name=NestedM,proto3" json:"NestedM,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// NestedMObj object map
	NestedMObj           map[string]*Nested `protobuf:"bytes,20,rep,name=NestedMObj,proto3" json:"NestedMObj,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}
func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

// Nested message definition
type Nested struct {
	// Str string field
	Str string `protobuf:"bytes,1,opt,name=Str,proto3" json:"Str,omitempty"`
	// Nested repeated nested messages
	Nested []*NestedLevel2 `protobuf:"bytes,2,rep,name=Nested,proto3" json:"Nested,omitempty"`
	// Nested map repeated nested messages
	NestedM map[string]string `protobuf:"bytes,3,rep,name=NestedM,proto3" json:"NestedM,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// NestedMObj nested object map
	NestedMObj           map[string]*NestedLevel2 `protobuf:"bytes,4,rep,name=NestedMObj,proto3" json:"NestedMObj,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Nested) Reset()         { *m = Nested{} }
func (m *Nested) String() string { return proto.CompactTextString(m) }
func (*Nested) ProtoMessage()    {}
func (*Nested) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}
func (m *Nested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nested.Unmarshal(m, b)
}
func (m *Nested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nested.Marshal(b, m, deterministic)
}
func (m *Nested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nested.Merge(m, src)
}
func (m *Nested) XXX_Size() int {
	return xxx_messageInfo_Nested.Size(m)
}
func (m *Nested) XXX_DiscardUnknown() {
	xxx_messageInfo_Nested.DiscardUnknown(m)
}

var xxx_messageInfo_Nested proto.InternalMessageInfo

// Message nested into nested message
type NestedLevel2 struct {
	// Str string field
	Str                  string   `protobuf:"bytes,1,opt,name=Str,proto3" json:"Str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NestedLevel2) Reset()         { *m = NestedLevel2{} }
func (m *NestedLevel2) String() string { return proto.CompactTextString(m) }
func (*NestedLevel2) ProtoMessage()    {}
func (*NestedLevel2) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}
func (m *NestedLevel2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NestedLevel2.Unmarshal(m, b)
}
func (m *NestedLevel2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NestedLevel2.Marshal(b, m, deterministic)
}
func (m *NestedLevel2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NestedLevel2.Merge(m, src)
}
func (m *NestedLevel2) XXX_Size() int {
	return xxx_messageInfo_NestedLevel2.Size(m)
}
func (m *NestedLevel2) XXX_DiscardUnknown() {
	xxx_messageInfo_NestedLevel2.DiscardUnknown(m)
}

var xxx_messageInfo_NestedLevel2 proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Test)(nil), "test.Test")
	proto.RegisterMapType((map[string]string)(nil), "test.Test.NestedMEntry")
	proto.RegisterMapType((map[string]*Nested)(nil), "test.Test.NestedMObjEntry")
	proto.RegisterType((*Nested)(nil), "test.Nested")
	proto.RegisterMapType((map[string]string)(nil), "test.Nested.NestedMEntry")
	proto.RegisterMapType((map[string]*NestedLevel2)(nil), "test.Nested.NestedMObjEntry")
	proto.RegisterType((*NestedLevel2)(nil), "test.NestedLevel2")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcf, 0x6e, 0x13, 0x3f,
	0x10, 0x8e, 0xb3, 0x9b, 0x7f, 0xee, 0xfe, 0xda, 0xfe, 0x4c, 0x05, 0x26, 0x42, 0x89, 0x55, 0x55,
	0x95, 0xc5, 0x21, 0x11, 0x49, 0x55, 0xa1, 0x88, 0x03, 0xbb, 0x04, 0x24, 0x04, 0x69, 0x85, 0x93,
	0x17, 0x48, 0x54, 0x13, 0xa5, 0xdd, 0xc4, 0xd1, 0xae, 0x53, 0x94, 0xb7, 0xe0, 0xc8, 0x81, 0x07,
	0xca, 0x91, 0x33, 0x87, 0x20, 0xfa, 0x18, 0x9c, 0x90, 0xed, 0xdd, 0x64, 0xb3, 0x09, 0xa2, 0x07,
	0x6e, 0xf3, 0xcd, 0x7c, 0xdf, 0x78, 0xe6, 0x93, 0x07, 0x42, 0xc9, 0x43, 0x59, 0x9b, 0x06, 0x42,
	0x0a, 0x64, 0xab, 0xb8, 0x7c, 0x34, 0x14, 0x43, 0xa1, 0x13, 0x75, 0x15, 0x99, 0x5a, 0xb9, 0x3a,
	0x14, 0x62, 0xe8, 0xf3, 0xba, 0x46, 0x83, 0xd9, 0xc7, 0xba, 0x1c, 0x8d, 0x79, 0x28, 0xfb, 0xe3,
	0x69, 0x44, 0xa8, 0xa4, 0x09, 0x9f, 0x82, 0xfe, 0x74, 0xca, 0x83, 0xd0, 0xd4, 0x8f, 0xbf, 0x16,
	0xa0, 0xdd, 0xe3, 0xa1, 0x44, 0x87, 0xd0, 0xea, 0xca, 0x00, 0x03, 0x02, 0x68, 0x89, 0xa9, 0x10,
	0x1d, 0xc1, 0xdc, 0xdb, 0x89, 0x6c, 0x36, 0x70, 0x96, 0x00, 0x9a, 0x63, 0x06, 0x44, 0xd9, 0xf3,
	0x33, 0x6c, 0x11, 0x40, 0x2d, 0x66, 0x80, 0xca, 0xbe, 0xf1, 0x45, 0x5f, 0x62, 0x9b, 0x00, 0x9a,
	0x65, 0x06, 0xa0, 0x87, 0x30, 0xdf, 0x16, 0xb3, 0x81, 0xcf, 0x71, 0x8e, 0x00, 0x0a, 0x58, 0x84,
	0x10, 0x82, 0xb6, 0x27, 0x84, 0x8f, 0xf3, 0x04, 0xd0, 0x22, 0xd3, 0xb1, 0xea, 0xe0, 0xcd, 0x25,
	0x0f, 0x71, 0x81, 0x00, 0xea, 0x30, 0x03, 0x90, 0x07, 0x4b, 0xbd, 0x78, 0x23, 0x5c, 0x24, 0x80,
	0xee, 0x35, 0xca, 0x35, 0xb3, 0x52, 0x2d, 0x5e, 0xa9, 0xb6, 0x62, 0x78, 0xc5, 0xc5, 0xb2, 0x9a,
	0xf9, 0xfc, 0xa3, 0x0a, 0xd8, 0x5a, 0x86, 0x4e, 0xe1, 0x5e, 0x7b, 0x16, 0xf4, 0xe5, 0x48, 0x4c,
	0xba, 0xf2, 0x0a, 0x97, 0xd4, 0xdc, 0x9e, 0xfd, 0x45, 0xb1, 0x92, 0x05, 0x74, 0x06, 0xf7, 0x63,
	0xf8, 0x6a, 0x16, 0x4a, 0x31, 0xc6, 0x50, 0x53, 0x9d, 0x5f, 0xcb, 0x6a, 0x31, 0xae, 0xb0, 0x14,
	0x07, 0xb5, 0x21, 0x5c, 0x3d, 0x75, 0x81, 0xf7, 0xee, 0x35, 0x22, 0xd0, 0x23, 0x26, 0x74, 0x08,
	0xc3, 0x42, 0x57, 0x06, 0xa3, 0xc9, 0xd0, 0xc5, 0x0e, 0xb1, 0x68, 0x89, 0xc5, 0x10, 0x9d, 0xc0,
	0x9c, 0xf2, 0xc7, 0xc5, 0xff, 0x11, 0x8b, 0x16, 0xbd, 0xfd, 0xef, 0xcb, 0x2a, 0x54, 0x09, 0xf3,
	0x3c, 0x33, 0x45, 0xe5, 0xb4, 0x36, 0xcc, 0xc5, 0xfb, 0xc4, 0xa2, 0x0e, 0x8b, 0x10, 0x7a, 0x99,
	0x98, 0xce, 0xc5, 0x07, 0xc4, 0xfa, 0xcb, 0x74, 0x76, 0x6a, 0x32, 0x17, 0x9d, 0xc3, 0x83, 0xcd,
	0x8d, 0x5d, 0x7c, 0x48, 0xac, 0x2d, 0x5b, 0xd2, 0x24, 0x74, 0x02, 0xf3, 0x17, 0x3c, 0x94, 0xfc,
	0x0a, 0xff, 0xaf, 0x3d, 0x71, 0x6a, 0xfa, 0x4b, 0x9b, 0x1c, 0x8b, 0x6a, 0xe8, 0x14, 0x16, 0x4c,
	0xe4, 0x62, 0xa4, 0x87, 0xdb, 0xa4, 0xc5, 0x45, 0xf4, 0x2c, 0xe6, 0x75, 0xf0, 0x03, 0xcd, 0x7b,
	0x64, 0x78, 0xbd, 0x35, 0xb9, 0xf3, 0x7a, 0x22, 0x83, 0x79, 0x2c, 0xe9, 0xa0, 0x16, 0x84, 0x51,
	0x78, 0x39, 0xb8, 0xc6, 0x47, 0xd1, 0xea, 0x5b, 0xaa, 0xcb, 0xc1, 0xb5, 0x11, 0x26, 0xd8, 0xe5,
	0x16, 0x74, 0x92, 0x4d, 0xd5, 0x71, 0xdc, 0xf0, 0x79, 0x7c, 0x1c, 0x37, 0x7c, 0xae, 0xbe, 0xeb,
	0x6d, 0xdf, 0x9f, 0x71, 0x7d, 0x1c, 0x25, 0x66, 0x40, 0x2b, 0xfb, 0x1c, 0x94, 0xdf, 0xc1, 0x83,
	0x54, 0xeb, 0x1d, 0xf2, 0xe3, 0xa4, 0x3c, 0xbd, 0xf5, 0xba, 0xd9, 0xf1, 0x22, 0x1b, 0xdb, 0xb8,
	0xe3, 0x40, 0x9f, 0xae, 0x2c, 0xce, 0xea, 0xed, 0x50, 0xb2, 0xcb, 0x7b, 0x7e, 0xcb, 0xfd, 0xc6,
	0xca, 0xe8, 0xe6, 0xda, 0x40, 0x4b, 0x93, 0x1f, 0x27, 0xc9, 0x7f, 0xb0, 0xf0, 0xc5, 0x86, 0x85,
	0xb6, 0xd6, 0x3d, 0xd9, 0xa5, 0xfb, 0xe7, 0x26, 0x7e, 0xb8, 0x8f, 0x89, 0x74, 0xd3, 0xc4, 0x5d,
	0xeb, 0x27, 0xac, 0x24, 0xf1, 0x38, 0xa6, 0xb4, 0xed, 0xa7, 0xe7, 0x2c, 0x7e, 0x56, 0x32, 0x8b,
	0xbb, 0x4a, 0xe6, 0xdb, 0x5d, 0x25, 0x33, 0xc8, 0xeb, 0xf3, 0x68, 0xfe, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0x11, 0x1a, 0xb6, 0x7b, 0x8b, 0x05, 0x00, 0x00,
}
