/*
Copyright 2015-2022 Gravitational, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: primitives.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gravitational_protoc_gen_terraform_v3_examples_types "github.com/gravitational/protoc-gen-terraform/v3/examples/types"
	github_com_hashicorp_terraform_plugin_framework_attr "github.com/hashicorp/terraform-plugin-framework/attr"
	github_com_hashicorp_terraform_plugin_framework_diag "github.com/hashicorp/terraform-plugin-framework/diag"
	github_com_hashicorp_terraform_plugin_framework_tfsdk "github.com/hashicorp/terraform-plugin-framework/tfsdk"
	github_com_hashicorp_terraform_plugin_framework_types "github.com/hashicorp/terraform-plugin-framework/types"
	github_com_hashicorp_terraform_plugin_go_tftypes "github.com/hashicorp/terraform-plugin-go/tftypes"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// GenSchemaPrimitives returns tfsdk.Schema definition for Primitives
func GenSchemaPrimitives(ctx context.Context) (github_com_hashicorp_terraform_plugin_framework_tfsdk.Schema, github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics) {
	return github_com_hashicorp_terraform_plugin_framework_tfsdk.Schema{Attributes: map[string]github_com_hashicorp_terraform_plugin_framework_tfsdk.Attribute{
		"bool_list": {
			Description: "bool_list bool list field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.ListType{ElemType: github_com_hashicorp_terraform_plugin_framework_types.BoolType},
		},
		"bool_value": {
			Description: "bool_value bool field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.BoolType,
		},
		"bytes_list": {
			Description: "bytes_list bytes list field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.ListType{ElemType: github_com_hashicorp_terraform_plugin_framework_types.StringType},
		},
		"bytes_value": {
			Description: "bytes_value bytes field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
		"double_list": {
			Description: "double_list double list field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.ListType{ElemType: github_com_hashicorp_terraform_plugin_framework_types.Float64Type},
		},
		"double_value": {
			Description: "double_value float64 field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.Float64Type,
		},
		"enum_list": {
			Description: "enum_list enum list field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.ListType{ElemType: github_com_hashicorp_terraform_plugin_framework_types.Int64Type},
		},
		"enum_value": {
			Description: "enum_value enum field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.Int64Type,
		},
		"float_list": {
			Description: "float_list float list field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.ListType{ElemType: github_com_hashicorp_terraform_plugin_framework_types.Float64Type},
		},
		"float_value": {
			Description: "float_value float32 field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.Float64Type,
		},
		"id": {
			Computed:      true,
			Description:   "",
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_tfsdk.UseStateForUnknown()},
			Type:          github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
		"int32_list": {
			Description: "int32_list int32 list field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.ListType{ElemType: github_com_hashicorp_terraform_plugin_framework_types.Int64Type},
		},
		"int32_value": {
			Description: "int32_value int32 field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.Int64Type,
		},
		"int64_list": {
			Description: "int64_list int64 list field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.ListType{ElemType: github_com_hashicorp_terraform_plugin_framework_types.Int64Type},
		},
		"int64_value": {
			Description: "int64_value int64 field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.Int64Type,
		},
		"string_list": {
			Description: "string_list string list field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.ListType{ElemType: github_com_hashicorp_terraform_plugin_framework_types.StringType},
		},
		"string_value": {
			Description: "string_value string field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
	}}, nil
}

// CopyPrimitivesFromTerraform copies contents of the source Terraform object into a target struct
func CopyPrimitivesFromTerraform(_ context.Context, tf github_com_hashicorp_terraform_plugin_framework_types.Object, obj *github_com_gravitational_protoc_gen_terraform_v3_examples_types.Primitives) github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics {
	var diags github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics
	{
		a, ok := tf.Attrs["bool_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.bool_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.bool_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.BoolList = make([]bool, len(v.Elems))
				if !v.Null && !v.Unknown {
					for k, a := range v.Elems {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Bool)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.bool_list", "github_com_hashicorp_terraform_plugin_framework_types.Bool"})
						} else {
							var t bool
							if !v.Null && !v.Unknown {
								t = bool(v.Value)
							}
							obj.BoolList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["bool_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.bool_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Bool)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.bool_value", "github.com/hashicorp/terraform-plugin-framework/types.Bool"})
			} else {
				var t bool
				if !v.Null && !v.Unknown {
					t = bool(v.Value)
				}
				obj.BoolValue = t
			}
		}
	}
	{
		a, ok := tf.Attrs["bytes_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.bytes_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.bytes_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.BytesList = make([][]byte, len(v.Elems))
				if !v.Null && !v.Unknown {
					for k, a := range v.Elems {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.bytes_list", "github_com_hashicorp_terraform_plugin_framework_types.String"})
						} else {
							var t []byte
							if !v.Null && !v.Unknown {
								t = []byte(v.Value)
							}
							obj.BytesList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["bytes_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.bytes_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.bytes_value", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t []byte
				if !v.Null && !v.Unknown {
					t = []byte(v.Value)
				}
				obj.BytesValue = t
			}
		}
	}
	{
		a, ok := tf.Attrs["double_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.double_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.double_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.DoubleList = make([]float64, len(v.Elems))
				if !v.Null && !v.Unknown {
					for k, a := range v.Elems {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Float64)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.double_list", "github_com_hashicorp_terraform_plugin_framework_types.Float64"})
						} else {
							var t float64
							if !v.Null && !v.Unknown {
								t = float64(v.Value)
							}
							obj.DoubleList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["double_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.double_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Float64)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.double_value", "github.com/hashicorp/terraform-plugin-framework/types.Float64"})
			} else {
				var t float64
				if !v.Null && !v.Unknown {
					t = float64(v.Value)
				}
				obj.DoubleValue = t
			}
		}
	}
	{
		a, ok := tf.Attrs["enum_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.enum_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.enum_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.EnumList = make([]github_com_gravitational_protoc_gen_terraform_v3_examples_types.EnumValue, len(v.Elems))
				if !v.Null && !v.Unknown {
					for k, a := range v.Elems {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.enum_list", "github_com_hashicorp_terraform_plugin_framework_types.Int64"})
						} else {
							var t github_com_gravitational_protoc_gen_terraform_v3_examples_types.EnumValue
							if !v.Null && !v.Unknown {
								t = github_com_gravitational_protoc_gen_terraform_v3_examples_types.EnumValue(v.Value)
							}
							obj.EnumList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["enum_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.enum_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.enum_value", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
			} else {
				var t github_com_gravitational_protoc_gen_terraform_v3_examples_types.EnumValue
				if !v.Null && !v.Unknown {
					t = github_com_gravitational_protoc_gen_terraform_v3_examples_types.EnumValue(v.Value)
				}
				obj.EnumValue = t
			}
		}
	}
	{
		a, ok := tf.Attrs["float_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.float_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.float_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.FloatList = make([]float32, len(v.Elems))
				if !v.Null && !v.Unknown {
					for k, a := range v.Elems {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Float64)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.float_list", "github_com_hashicorp_terraform_plugin_framework_types.Float64"})
						} else {
							var t float32
							if !v.Null && !v.Unknown {
								t = float32(v.Value)
							}
							obj.FloatList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["float_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.float_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Float64)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.float_value", "github.com/hashicorp/terraform-plugin-framework/types.Float64"})
			} else {
				var t float32
				if !v.Null && !v.Unknown {
					t = float32(v.Value)
				}
				obj.FloatValue = t
			}
		}
	}
	{
		a, ok := tf.Attrs["id"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.id"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.id", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.Null && !v.Unknown {
					t = string(v.Value)
				}
				obj.Id = t
			}
		}
	}
	{
		a, ok := tf.Attrs["int32_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.int32_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.int32_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.Int32List = make([]int32, len(v.Elems))
				if !v.Null && !v.Unknown {
					for k, a := range v.Elems {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.int32_list", "github_com_hashicorp_terraform_plugin_framework_types.Int64"})
						} else {
							var t int32
							if !v.Null && !v.Unknown {
								t = int32(v.Value)
							}
							obj.Int32List[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["int32_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.int32_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.int32_value", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
			} else {
				var t int32
				if !v.Null && !v.Unknown {
					t = int32(v.Value)
				}
				obj.Int32Value = t
			}
		}
	}
	{
		a, ok := tf.Attrs["int64_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.int64_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.int64_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.Int64List = make([]int64, len(v.Elems))
				if !v.Null && !v.Unknown {
					for k, a := range v.Elems {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.int64_list", "github_com_hashicorp_terraform_plugin_framework_types.Int64"})
						} else {
							var t int64
							if !v.Null && !v.Unknown {
								t = int64(v.Value)
							}
							obj.Int64List[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["int64_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.int64_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.int64_value", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
			} else {
				var t int64
				if !v.Null && !v.Unknown {
					t = int64(v.Value)
				}
				obj.Int64Value = t
			}
		}
	}
	{
		a, ok := tf.Attrs["string_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.string_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.string_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.StringList = make([]string, len(v.Elems))
				if !v.Null && !v.Unknown {
					for k, a := range v.Elems {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.string_list", "github_com_hashicorp_terraform_plugin_framework_types.String"})
						} else {
							var t string
							if !v.Null && !v.Unknown {
								t = string(v.Value)
							}
							obj.StringList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["string_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.string_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.string_value", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.Null && !v.Unknown {
					t = string(v.Value)
				}
				obj.StringValue = t
			}
		}
	}
	return diags
}

// CopyPrimitivesToTerraform copies contents of the source Terraform object into a target struct
func CopyPrimitivesToTerraform(ctx context.Context, obj *github_com_gravitational_protoc_gen_terraform_v3_examples_types.Primitives, tf *github_com_hashicorp_terraform_plugin_framework_types.Object) github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics {
	var diags github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics
	tf.Null = false
	tf.Unknown = false
	if tf.Attrs == nil {
		tf.Attrs = make(map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value)
	}
	{
		a, ok := tf.AttrTypes["bool_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.bool_list"})
		} else {
			o, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.bool_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				c, ok := tf.Attrs["bool_list"].(github_com_hashicorp_terraform_plugin_framework_types.List)
				if !ok {
					c = github_com_hashicorp_terraform_plugin_framework_types.List{

						ElemType: o.ElemType,
						Elems:    make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.BoolList)),
						Null:     true,
					}
				} else {
					if c.Elems == nil {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.BoolList))
					}
				}
				if obj.BoolList != nil {
					t := o.ElemType
					if len(obj.BoolList) != len(c.Elems) {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.BoolList))
					}
					for k, a := range obj.BoolList {
						v, ok := c.Elems[k].(github_com_hashicorp_terraform_plugin_framework_types.Bool)
						if !ok {
							i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
							if err != nil {
								diags.Append(attrWriteGeneralError{"Primitives.bool_list", err})
							}
							v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Bool)
							if !ok {
								diags.Append(attrWriteConversionFailureDiag{"Primitives.bool_list", "github.com/hashicorp/terraform-plugin-framework/types.Bool"})
							}
							v.Null = bool(a) == false
						}
						v.Value = bool(a)
						v.Unknown = false
						c.Elems[k] = v
					}
					if len(obj.BoolList) > 0 {
						c.Null = false
					}
				}
				c.Unknown = false
				tf.Attrs["bool_list"] = c
			}
		}
	}
	{
		t, ok := tf.AttrTypes["bool_value"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.bool_value"})
		} else {
			v, ok := tf.Attrs["bool_value"].(github_com_hashicorp_terraform_plugin_framework_types.Bool)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Primitives.bool_value", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Bool)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Primitives.bool_value", "github.com/hashicorp/terraform-plugin-framework/types.Bool"})
				}
				v.Null = bool(obj.BoolValue) == false
			}
			v.Value = bool(obj.BoolValue)
			v.Unknown = false
			tf.Attrs["bool_value"] = v
		}
	}
	{
		a, ok := tf.AttrTypes["bytes_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.bytes_list"})
		} else {
			o, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.bytes_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				c, ok := tf.Attrs["bytes_list"].(github_com_hashicorp_terraform_plugin_framework_types.List)
				if !ok {
					c = github_com_hashicorp_terraform_plugin_framework_types.List{

						ElemType: o.ElemType,
						Elems:    make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.BytesList)),
						Null:     true,
					}
				} else {
					if c.Elems == nil {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.BytesList))
					}
				}
				if obj.BytesList != nil {
					t := o.ElemType
					if len(obj.BytesList) != len(c.Elems) {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.BytesList))
					}
					for k, a := range obj.BytesList {
						v, ok := c.Elems[k].(github_com_hashicorp_terraform_plugin_framework_types.String)
						if !ok {
							i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
							if err != nil {
								diags.Append(attrWriteGeneralError{"Primitives.bytes_list", err})
							}
							v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
							if !ok {
								diags.Append(attrWriteConversionFailureDiag{"Primitives.bytes_list", "github.com/hashicorp/terraform-plugin-framework/types.String"})
							}
							v.Null = string(a) == ""
						}
						v.Value = string(a)
						v.Unknown = false
						c.Elems[k] = v
					}
					if len(obj.BytesList) > 0 {
						c.Null = false
					}
				}
				c.Unknown = false
				tf.Attrs["bytes_list"] = c
			}
		}
	}
	{
		t, ok := tf.AttrTypes["bytes_value"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.bytes_value"})
		} else {
			v, ok := tf.Attrs["bytes_value"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Primitives.bytes_value", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Primitives.bytes_value", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = string(obj.BytesValue) == ""
			}
			v.Value = string(obj.BytesValue)
			v.Unknown = false
			tf.Attrs["bytes_value"] = v
		}
	}
	{
		a, ok := tf.AttrTypes["double_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.double_list"})
		} else {
			o, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.double_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				c, ok := tf.Attrs["double_list"].(github_com_hashicorp_terraform_plugin_framework_types.List)
				if !ok {
					c = github_com_hashicorp_terraform_plugin_framework_types.List{

						ElemType: o.ElemType,
						Elems:    make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.DoubleList)),
						Null:     true,
					}
				} else {
					if c.Elems == nil {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.DoubleList))
					}
				}
				if obj.DoubleList != nil {
					t := o.ElemType
					if len(obj.DoubleList) != len(c.Elems) {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.DoubleList))
					}
					for k, a := range obj.DoubleList {
						v, ok := c.Elems[k].(github_com_hashicorp_terraform_plugin_framework_types.Float64)
						if !ok {
							i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
							if err != nil {
								diags.Append(attrWriteGeneralError{"Primitives.double_list", err})
							}
							v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Float64)
							if !ok {
								diags.Append(attrWriteConversionFailureDiag{"Primitives.double_list", "github.com/hashicorp/terraform-plugin-framework/types.Float64"})
							}
							v.Null = float64(a) == 0
						}
						v.Value = float64(a)
						v.Unknown = false
						c.Elems[k] = v
					}
					if len(obj.DoubleList) > 0 {
						c.Null = false
					}
				}
				c.Unknown = false
				tf.Attrs["double_list"] = c
			}
		}
	}
	{
		t, ok := tf.AttrTypes["double_value"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.double_value"})
		} else {
			v, ok := tf.Attrs["double_value"].(github_com_hashicorp_terraform_plugin_framework_types.Float64)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Primitives.double_value", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Float64)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Primitives.double_value", "github.com/hashicorp/terraform-plugin-framework/types.Float64"})
				}
				v.Null = float64(obj.DoubleValue) == 0
			}
			v.Value = float64(obj.DoubleValue)
			v.Unknown = false
			tf.Attrs["double_value"] = v
		}
	}
	{
		a, ok := tf.AttrTypes["enum_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.enum_list"})
		} else {
			o, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.enum_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				c, ok := tf.Attrs["enum_list"].(github_com_hashicorp_terraform_plugin_framework_types.List)
				if !ok {
					c = github_com_hashicorp_terraform_plugin_framework_types.List{

						ElemType: o.ElemType,
						Elems:    make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.EnumList)),
						Null:     true,
					}
				} else {
					if c.Elems == nil {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.EnumList))
					}
				}
				if obj.EnumList != nil {
					t := o.ElemType
					if len(obj.EnumList) != len(c.Elems) {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.EnumList))
					}
					for k, a := range obj.EnumList {
						v, ok := c.Elems[k].(github_com_hashicorp_terraform_plugin_framework_types.Int64)
						if !ok {
							i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
							if err != nil {
								diags.Append(attrWriteGeneralError{"Primitives.enum_list", err})
							}
							v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
							if !ok {
								diags.Append(attrWriteConversionFailureDiag{"Primitives.enum_list", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
							}
							v.Null = int64(a) == 0
						}
						v.Value = int64(a)
						v.Unknown = false
						c.Elems[k] = v
					}
					if len(obj.EnumList) > 0 {
						c.Null = false
					}
				}
				c.Unknown = false
				tf.Attrs["enum_list"] = c
			}
		}
	}
	{
		t, ok := tf.AttrTypes["enum_value"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.enum_value"})
		} else {
			v, ok := tf.Attrs["enum_value"].(github_com_hashicorp_terraform_plugin_framework_types.Int64)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Primitives.enum_value", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Primitives.enum_value", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
				}
				v.Null = int64(obj.EnumValue) == 0
			}
			v.Value = int64(obj.EnumValue)
			v.Unknown = false
			tf.Attrs["enum_value"] = v
		}
	}
	{
		a, ok := tf.AttrTypes["float_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.float_list"})
		} else {
			o, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.float_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				c, ok := tf.Attrs["float_list"].(github_com_hashicorp_terraform_plugin_framework_types.List)
				if !ok {
					c = github_com_hashicorp_terraform_plugin_framework_types.List{

						ElemType: o.ElemType,
						Elems:    make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.FloatList)),
						Null:     true,
					}
				} else {
					if c.Elems == nil {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.FloatList))
					}
				}
				if obj.FloatList != nil {
					t := o.ElemType
					if len(obj.FloatList) != len(c.Elems) {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.FloatList))
					}
					for k, a := range obj.FloatList {
						v, ok := c.Elems[k].(github_com_hashicorp_terraform_plugin_framework_types.Float64)
						if !ok {
							i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
							if err != nil {
								diags.Append(attrWriteGeneralError{"Primitives.float_list", err})
							}
							v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Float64)
							if !ok {
								diags.Append(attrWriteConversionFailureDiag{"Primitives.float_list", "github.com/hashicorp/terraform-plugin-framework/types.Float64"})
							}
							v.Null = float64(a) == 0
						}
						v.Value = float64(a)
						v.Unknown = false
						c.Elems[k] = v
					}
					if len(obj.FloatList) > 0 {
						c.Null = false
					}
				}
				c.Unknown = false
				tf.Attrs["float_list"] = c
			}
		}
	}
	{
		t, ok := tf.AttrTypes["float_value"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.float_value"})
		} else {
			v, ok := tf.Attrs["float_value"].(github_com_hashicorp_terraform_plugin_framework_types.Float64)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Primitives.float_value", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Float64)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Primitives.float_value", "github.com/hashicorp/terraform-plugin-framework/types.Float64"})
				}
				v.Null = float64(obj.FloatValue) == 0
			}
			v.Value = float64(obj.FloatValue)
			v.Unknown = false
			tf.Attrs["float_value"] = v
		}
	}
	{
		t, ok := tf.AttrTypes["id"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.id"})
		} else {
			v, ok := tf.Attrs["id"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Primitives.id", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Primitives.id", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = false
			}
			v.Value = string(obj.Id)
			v.Unknown = false
			tf.Attrs["id"] = v
		}
	}
	{
		a, ok := tf.AttrTypes["int32_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.int32_list"})
		} else {
			o, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.int32_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				c, ok := tf.Attrs["int32_list"].(github_com_hashicorp_terraform_plugin_framework_types.List)
				if !ok {
					c = github_com_hashicorp_terraform_plugin_framework_types.List{

						ElemType: o.ElemType,
						Elems:    make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.Int32List)),
						Null:     true,
					}
				} else {
					if c.Elems == nil {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.Int32List))
					}
				}
				if obj.Int32List != nil {
					t := o.ElemType
					if len(obj.Int32List) != len(c.Elems) {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.Int32List))
					}
					for k, a := range obj.Int32List {
						v, ok := c.Elems[k].(github_com_hashicorp_terraform_plugin_framework_types.Int64)
						if !ok {
							i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
							if err != nil {
								diags.Append(attrWriteGeneralError{"Primitives.int32_list", err})
							}
							v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
							if !ok {
								diags.Append(attrWriteConversionFailureDiag{"Primitives.int32_list", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
							}
							v.Null = int64(a) == 0
						}
						v.Value = int64(a)
						v.Unknown = false
						c.Elems[k] = v
					}
					if len(obj.Int32List) > 0 {
						c.Null = false
					}
				}
				c.Unknown = false
				tf.Attrs["int32_list"] = c
			}
		}
	}
	{
		t, ok := tf.AttrTypes["int32_value"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.int32_value"})
		} else {
			v, ok := tf.Attrs["int32_value"].(github_com_hashicorp_terraform_plugin_framework_types.Int64)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Primitives.int32_value", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Primitives.int32_value", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
				}
				v.Null = int64(obj.Int32Value) == 0
			}
			v.Value = int64(obj.Int32Value)
			v.Unknown = false
			tf.Attrs["int32_value"] = v
		}
	}
	{
		a, ok := tf.AttrTypes["int64_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.int64_list"})
		} else {
			o, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.int64_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				c, ok := tf.Attrs["int64_list"].(github_com_hashicorp_terraform_plugin_framework_types.List)
				if !ok {
					c = github_com_hashicorp_terraform_plugin_framework_types.List{

						ElemType: o.ElemType,
						Elems:    make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.Int64List)),
						Null:     true,
					}
				} else {
					if c.Elems == nil {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.Int64List))
					}
				}
				if obj.Int64List != nil {
					t := o.ElemType
					if len(obj.Int64List) != len(c.Elems) {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.Int64List))
					}
					for k, a := range obj.Int64List {
						v, ok := c.Elems[k].(github_com_hashicorp_terraform_plugin_framework_types.Int64)
						if !ok {
							i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
							if err != nil {
								diags.Append(attrWriteGeneralError{"Primitives.int64_list", err})
							}
							v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
							if !ok {
								diags.Append(attrWriteConversionFailureDiag{"Primitives.int64_list", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
							}
							v.Null = int64(a) == 0
						}
						v.Value = int64(a)
						v.Unknown = false
						c.Elems[k] = v
					}
					if len(obj.Int64List) > 0 {
						c.Null = false
					}
				}
				c.Unknown = false
				tf.Attrs["int64_list"] = c
			}
		}
	}
	{
		t, ok := tf.AttrTypes["int64_value"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.int64_value"})
		} else {
			v, ok := tf.Attrs["int64_value"].(github_com_hashicorp_terraform_plugin_framework_types.Int64)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Primitives.int64_value", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Primitives.int64_value", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
				}
				v.Null = int64(obj.Int64Value) == 0
			}
			v.Value = int64(obj.Int64Value)
			v.Unknown = false
			tf.Attrs["int64_value"] = v
		}
	}
	{
		a, ok := tf.AttrTypes["string_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.string_list"})
		} else {
			o, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.string_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				c, ok := tf.Attrs["string_list"].(github_com_hashicorp_terraform_plugin_framework_types.List)
				if !ok {
					c = github_com_hashicorp_terraform_plugin_framework_types.List{

						ElemType: o.ElemType,
						Elems:    make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.StringList)),
						Null:     true,
					}
				} else {
					if c.Elems == nil {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.StringList))
					}
				}
				if obj.StringList != nil {
					t := o.ElemType
					if len(obj.StringList) != len(c.Elems) {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.StringList))
					}
					for k, a := range obj.StringList {
						v, ok := c.Elems[k].(github_com_hashicorp_terraform_plugin_framework_types.String)
						if !ok {
							i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
							if err != nil {
								diags.Append(attrWriteGeneralError{"Primitives.string_list", err})
							}
							v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
							if !ok {
								diags.Append(attrWriteConversionFailureDiag{"Primitives.string_list", "github.com/hashicorp/terraform-plugin-framework/types.String"})
							}
							v.Null = string(a) == ""
						}
						v.Value = string(a)
						v.Unknown = false
						c.Elems[k] = v
					}
					if len(obj.StringList) > 0 {
						c.Null = false
					}
				}
				c.Unknown = false
				tf.Attrs["string_list"] = c
			}
		}
	}
	{
		t, ok := tf.AttrTypes["string_value"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.string_value"})
		} else {
			v, ok := tf.Attrs["string_value"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Primitives.string_value", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Primitives.string_value", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = string(obj.StringValue) == ""
			}
			v.Value = string(obj.StringValue)
			v.Unknown = false
			tf.Attrs["string_value"] = v
		}
	}
	return diags
}

// attrReadMissingDiag represents diagnostic message on an attribute missing in the source object
type attrReadMissingDiag struct {
	Path string
}

func (d attrReadMissingDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrReadMissingDiag) Summary() string {
	return "Error reading from Terraform object"
}

func (d attrReadMissingDiag) Detail() string {
	return fmt.Sprintf("A value for %v is missing in the source Terraform object Attrs", d.Path)
}

func (d attrReadMissingDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrReadConversionFailureDiag represents diagnostic message on a failed type conversion on read
type attrReadConversionFailureDiag struct {
	Path string
	Type string
}

func (d attrReadConversionFailureDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrReadConversionFailureDiag) Summary() string {
	return "Error reading from Terraform object"
}

func (d attrReadConversionFailureDiag) Detail() string {
	return fmt.Sprintf("A value for %v can not be converted to %v", d.Path, d.Type)
}

func (d attrReadConversionFailureDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteMissingDiag represents diagnostic message on an attribute missing in the target object
type attrWriteMissingDiag struct {
	Path string
}

func (d attrWriteMissingDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteMissingDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteMissingDiag) Detail() string {
	return fmt.Sprintf("A value for %v is missing in the source Terraform object AttrTypes", d.Path)
}

func (d attrWriteMissingDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteConversionFailureDiag represents diagnostic message on a failed type conversion on write
type attrWriteConversionFailureDiag struct {
	Path string
	Type string
}

func (d attrWriteConversionFailureDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteConversionFailureDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteConversionFailureDiag) Detail() string {
	return fmt.Sprintf("A value for %v can not be converted to %v", d.Path, d.Type)
}

func (d attrWriteConversionFailureDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteGeneralError represents diagnostic message on a generic error on write
type attrWriteGeneralError struct {
	Path string
	Err  error
}

func (d attrWriteGeneralError) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteGeneralError) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteGeneralError) Detail() string {
	return fmt.Sprintf("%s: %s", d.Path, d.Err.Error())
}

func (d attrWriteGeneralError) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}
