/*
Copyright 2015-2026 Gravitational, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: primitives.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gravitational_protoc_gen_terraform_v4_examples_types "github.com/gravitational/protoc-gen-terraform/v4/examples/types"
	github_com_hashicorp_terraform_plugin_framework_attr "github.com/hashicorp/terraform-plugin-framework/attr"
	github_com_hashicorp_terraform_plugin_framework_diag "github.com/hashicorp/terraform-plugin-framework/diag"
	github_com_hashicorp_terraform_plugin_framework_resource "github.com/hashicorp/terraform-plugin-framework/resource"
	github_com_hashicorp_terraform_plugin_framework_resource_schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	github_com_hashicorp_terraform_plugin_framework_tfsdk "github.com/hashicorp/terraform-plugin-framework/tfsdk"
	github_com_hashicorp_terraform_plugin_framework_types "github.com/hashicorp/terraform-plugin-framework/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// GenSchemaPrimitives returns tfsdk.Schema definition for Primitives
func GenSchemaPrimitives(ctx context.Context) (github_com_hashicorp_terraform_plugin_framework_resource_schema.Schema, github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics) {
	return github_com_hashicorp_terraform_plugin_framework_resource_schema.Schema{Attributes: map[string]github_com_hashicorp_terraform_plugin_framework_resource_schema.Attribute{
		"bool_list": github_com_hashicorp_terraform_plugin_framework_resource_schema.ListAttribute{
			Computed:      true,
			Description:   "bool_list bool list field.",
			ElementType:   github_com_hashicorp_terraform_plugin_framework_types.BoolType,
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"bool_value": github_com_hashicorp_terraform_plugin_framework_resource_schema.BoolAttribute{
			Computed:      true,
			Description:   "bool_value bool field.",
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"bytes_list": github_com_hashicorp_terraform_plugin_framework_resource_schema.ListAttribute{
			Computed:      true,
			Description:   "bytes_list bytes list field.",
			ElementType:   github_com_hashicorp_terraform_plugin_framework_types.StringType,
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"bytes_value": github_com_hashicorp_terraform_plugin_framework_resource_schema.StringAttribute{
			Computed:      true,
			Description:   "bytes_value bytes field.",
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"double_list": github_com_hashicorp_terraform_plugin_framework_resource_schema.ListAttribute{
			Computed:      true,
			Description:   "double_list double list field.",
			ElementType:   github_com_hashicorp_terraform_plugin_framework_types.Float64Type,
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"double_value": github_com_hashicorp_terraform_plugin_framework_resource_schema.Float64Attribute{
			Computed:      true,
			Description:   "double_value float64 field.",
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"enum_list": github_com_hashicorp_terraform_plugin_framework_resource_schema.ListAttribute{
			Computed:      true,
			Description:   "enum_list enum list field.",
			ElementType:   github_com_hashicorp_terraform_plugin_framework_types.Int64Type,
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"enum_value": github_com_hashicorp_terraform_plugin_framework_resource_schema.Int64Attribute{
			Computed:      true,
			Description:   "enum_value enum field.",
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"float_list": github_com_hashicorp_terraform_plugin_framework_resource_schema.ListAttribute{
			Computed:      true,
			Description:   "float_list float list field.",
			ElementType:   github_com_hashicorp_terraform_plugin_framework_types.Float64Type,
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"float_value": github_com_hashicorp_terraform_plugin_framework_resource_schema.Float64Attribute{
			Computed:      true,
			Description:   "float_value float32 field.",
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"id": github_com_hashicorp_terraform_plugin_framework_resource_schema.StringAttribute{
			Computed:      true,
			Description:   "",
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"int32_list": github_com_hashicorp_terraform_plugin_framework_resource_schema.ListAttribute{
			Computed:      true,
			Description:   "int32_list int32 list field.",
			ElementType:   github_com_hashicorp_terraform_plugin_framework_types.Int64Type,
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"int32_value": github_com_hashicorp_terraform_plugin_framework_resource_schema.Int64Attribute{
			Computed:      true,
			Description:   "int32_value int32 field.",
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"int64_list": github_com_hashicorp_terraform_plugin_framework_resource_schema.ListAttribute{
			Computed:      true,
			Description:   "int64_list int64 list field.",
			ElementType:   github_com_hashicorp_terraform_plugin_framework_types.Int64Type,
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"int64_value": github_com_hashicorp_terraform_plugin_framework_resource_schema.Int64Attribute{
			Computed:      true,
			Description:   "int64_value int64 field.",
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"string_list": github_com_hashicorp_terraform_plugin_framework_resource_schema.ListAttribute{
			Computed:      true,
			Description:   "string_list string list field.",
			ElementType:   github_com_hashicorp_terraform_plugin_framework_types.StringType,
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
		"string_value": github_com_hashicorp_terraform_plugin_framework_resource_schema.StringAttribute{
			Computed:      true,
			Description:   "string_value string field.",
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_resource.UseStateForUnknown()},
		},
	}}, nil
}

// CopyPrimitivesFromTerraform copies contents of the source Terraform object into a target struct
func CopyPrimitivesFromTerraform(_ context.Context, tf github_com_hashicorp_terraform_plugin_framework_types.Object, obj *github_com_gravitational_protoc_gen_terraform_v4_examples_types.Primitives) github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics {
	var diags github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics
	{
		a, ok := tf.Attributes()["bool_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.bool_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.bool_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.BoolList = make([]bool, len(v.Elements()))
				if !v.IsNull() && !v.IsUnknown() {
					for k, a := range v.Elements() {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Bool)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.bool_list", "github_com_hashicorp_terraform_plugin_framework_types.Bool"})
						} else {
							var t bool
							if !v.IsNull() && !v.IsUnknown() {
								t = (v.ValueBool())
							}
							obj.BoolList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attributes()["bool_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.bool_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Bool)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.bool_value", "github.com/hashicorp/terraform-plugin-framework/types.Bool"})
			} else {
				var t bool
				if !v.IsNull() && !v.IsUnknown() {
					t = (v.ValueBool())
				}
				obj.BoolValue = t
			}
		}
	}
	{
		a, ok := tf.Attributes()["bytes_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.bytes_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.bytes_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.BytesList = make([][]byte, len(v.Elements()))
				if !v.IsNull() && !v.IsUnknown() {
					for k, a := range v.Elements() {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.bytes_list", "github_com_hashicorp_terraform_plugin_framework_types.String"})
						} else {
							var t []byte
							if !v.IsNull() && !v.IsUnknown() {
								t = []byte(v.ValueString())
							}
							obj.BytesList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attributes()["bytes_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.bytes_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.bytes_value", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t []byte
				if !v.IsNull() && !v.IsUnknown() {
					t = []byte(v.ValueString())
				}
				obj.BytesValue = t
			}
		}
	}
	{
		a, ok := tf.Attributes()["double_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.double_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.double_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.DoubleList = make([]float64, len(v.Elements()))
				if !v.IsNull() && !v.IsUnknown() {
					for k, a := range v.Elements() {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Float64)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.double_list", "github_com_hashicorp_terraform_plugin_framework_types.Float64"})
						} else {
							var t float64
							if !v.IsNull() && !v.IsUnknown() {
								t = (v.ValueFloat64())
							}
							obj.DoubleList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attributes()["double_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.double_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Float64)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.double_value", "github.com/hashicorp/terraform-plugin-framework/types.Float64"})
			} else {
				var t float64
				if !v.IsNull() && !v.IsUnknown() {
					t = (v.ValueFloat64())
				}
				obj.DoubleValue = t
			}
		}
	}
	{
		a, ok := tf.Attributes()["enum_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.enum_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.enum_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.EnumList = make([]github_com_gravitational_protoc_gen_terraform_v4_examples_types.EnumValue, len(v.Elements()))
				if !v.IsNull() && !v.IsUnknown() {
					for k, a := range v.Elements() {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.enum_list", "github_com_hashicorp_terraform_plugin_framework_types.Int64"})
						} else {
							var t github_com_gravitational_protoc_gen_terraform_v4_examples_types.EnumValue
							if !v.IsNull() && !v.IsUnknown() {
								t = github_com_gravitational_protoc_gen_terraform_v4_examples_types.EnumValue(v.ValueInt64())
							}
							obj.EnumList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attributes()["enum_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.enum_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.enum_value", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
			} else {
				var t github_com_gravitational_protoc_gen_terraform_v4_examples_types.EnumValue
				if !v.IsNull() && !v.IsUnknown() {
					t = github_com_gravitational_protoc_gen_terraform_v4_examples_types.EnumValue(v.ValueInt64())
				}
				obj.EnumValue = t
			}
		}
	}
	{
		a, ok := tf.Attributes()["float_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.float_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.float_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.FloatList = make([]float32, len(v.Elements()))
				if !v.IsNull() && !v.IsUnknown() {
					for k, a := range v.Elements() {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Float64)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.float_list", "github_com_hashicorp_terraform_plugin_framework_types.Float64"})
						} else {
							var t float32
							if !v.IsNull() && !v.IsUnknown() {
								t = float32(v.ValueFloat64())
							}
							obj.FloatList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attributes()["float_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.float_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Float64)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.float_value", "github.com/hashicorp/terraform-plugin-framework/types.Float64"})
			} else {
				var t float32
				if !v.IsNull() && !v.IsUnknown() {
					t = float32(v.ValueFloat64())
				}
				obj.FloatValue = t
			}
		}
	}
	{
		a, ok := tf.Attributes()["id"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.id"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.id", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.IsNull() && !v.IsUnknown() {
					t = (v.ValueString())
				}
				obj.Id = t
			}
		}
	}
	{
		a, ok := tf.Attributes()["int32_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.int32_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.int32_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.Int32List = make([]int32, len(v.Elements()))
				if !v.IsNull() && !v.IsUnknown() {
					for k, a := range v.Elements() {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.int32_list", "github_com_hashicorp_terraform_plugin_framework_types.Int64"})
						} else {
							var t int32
							if !v.IsNull() && !v.IsUnknown() {
								t = int32(v.ValueInt64())
							}
							obj.Int32List[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attributes()["int32_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.int32_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.int32_value", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
			} else {
				var t int32
				if !v.IsNull() && !v.IsUnknown() {
					t = int32(v.ValueInt64())
				}
				obj.Int32Value = t
			}
		}
	}
	{
		a, ok := tf.Attributes()["int64_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.int64_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.int64_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.Int64List = make([]int64, len(v.Elements()))
				if !v.IsNull() && !v.IsUnknown() {
					for k, a := range v.Elements() {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.int64_list", "github_com_hashicorp_terraform_plugin_framework_types.Int64"})
						} else {
							var t int64
							if !v.IsNull() && !v.IsUnknown() {
								t = (v.ValueInt64())
							}
							obj.Int64List[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attributes()["int64_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.int64_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.Int64)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.int64_value", "github.com/hashicorp/terraform-plugin-framework/types.Int64"})
			} else {
				var t int64
				if !v.IsNull() && !v.IsUnknown() {
					t = (v.ValueInt64())
				}
				obj.Int64Value = t
			}
		}
	}
	{
		a, ok := tf.Attributes()["string_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.string_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.string_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.StringList = make([]string, len(v.Elements()))
				if !v.IsNull() && !v.IsUnknown() {
					for k, a := range v.Elements() {
						v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Primitives.string_list", "github_com_hashicorp_terraform_plugin_framework_types.String"})
						} else {
							var t string
							if !v.IsNull() && !v.IsUnknown() {
								t = (v.ValueString())
							}
							obj.StringList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attributes()["string_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Primitives.string_value"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Primitives.string_value", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.IsNull() && !v.IsUnknown() {
					t = (v.ValueString())
				}
				obj.StringValue = t
			}
		}
	}
	return diags
}

// CopyPrimitivesToTerraform copies contents of source struct into a Terraform object.
func CopyPrimitivesToTerraform(ctx context.Context, obj *github_com_gravitational_protoc_gen_terraform_v4_examples_types.Primitives, tf *github_com_hashicorp_terraform_plugin_framework_types.Object) (github_com_hashicorp_terraform_plugin_framework_types.Object, github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics) {
	return CopyPrimitivesToTerraformPreserveUnknown(ctx, obj, tf, false)
}

// CopyPrimitivesToTerraformPreserveUnknown copies contents of source struct into a Terraform object.
// Set preserveUnknown to true to preserve unknown values.
func CopyPrimitivesToTerraformPreserveUnknown(ctx context.Context, obj *github_com_gravitational_protoc_gen_terraform_v4_examples_types.Primitives, tf *github_com_hashicorp_terraform_plugin_framework_types.Object, preserveUnknown bool) (github_com_hashicorp_terraform_plugin_framework_types.Object, github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics) {
	schema, diags := GenSchemaPrimitives(ctx)
	if diags.HasError() {
		return github_com_hashicorp_terraform_plugin_framework_types.Object{}, diags
	}
	attrType := schema.Type().(github_com_hashicorp_terraform_plugin_framework_types.ObjectType)
	var attrs map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value
	if tf == nil || tf.Attributes() == nil {
		attrs = make(map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value)
	} else {
		attrs = tf.Attributes()
	}
	{
		attrType, ok := attrType.AttributeTypes()["bool_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.bool_list"})
		} else {
			attrType, ok := attrType.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.bool_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				var v github_com_hashicorp_terraform_plugin_framework_attr.Value
				existing := attrs["bool_list"]
				if preserveUnknown && existing != nil && existing.IsUnknown() {
					v = github_com_hashicorp_terraform_plugin_framework_types.ListUnknown(attrType.ElementType())
				} else {
					oldElems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.BoolList))
					c, ok := existing.(github_com_hashicorp_terraform_plugin_framework_types.List)
					if ok && c.Elements() != nil {
						oldElems = c.Elements()
					}
					elems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.BoolList))
					copy(elems, oldElems)
					for k, a := range obj.BoolList {
						var v github_com_hashicorp_terraform_plugin_framework_attr.Value
						existing := elems[k]
						if preserveUnknown && existing != nil && existing.IsUnknown() {
							v = github_com_hashicorp_terraform_plugin_framework_types.BoolUnknown()
						} else {
							v = github_com_hashicorp_terraform_plugin_framework_types.BoolValue(bool(a))
						}
						elems[k] = v
					}
					result, resultDiags := github_com_hashicorp_terraform_plugin_framework_types.ListValue(attrType.ElementType(), elems)
					diags.Append(resultDiags...)
					v = result
				}
				attrs["bool_list"] = v
			}
		}
	}
	{
		var v github_com_hashicorp_terraform_plugin_framework_attr.Value
		existing := attrs["bool_value"]
		if preserveUnknown && existing != nil && existing.IsUnknown() {
			v = github_com_hashicorp_terraform_plugin_framework_types.BoolUnknown()
		} else {
			v = github_com_hashicorp_terraform_plugin_framework_types.BoolValue(bool(obj.BoolValue))
		}
		attrs["bool_value"] = v
	}
	{
		attrType, ok := attrType.AttributeTypes()["bytes_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.bytes_list"})
		} else {
			attrType, ok := attrType.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.bytes_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				var v github_com_hashicorp_terraform_plugin_framework_attr.Value
				existing := attrs["bytes_list"]
				if preserveUnknown && existing != nil && existing.IsUnknown() {
					v = github_com_hashicorp_terraform_plugin_framework_types.ListUnknown(attrType.ElementType())
				} else {
					oldElems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.BytesList))
					c, ok := existing.(github_com_hashicorp_terraform_plugin_framework_types.List)
					if ok && c.Elements() != nil {
						oldElems = c.Elements()
					}
					elems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.BytesList))
					copy(elems, oldElems)
					for k, a := range obj.BytesList {
						var v github_com_hashicorp_terraform_plugin_framework_attr.Value
						existing := elems[k]
						if preserveUnknown && existing != nil && existing.IsUnknown() {
							v = github_com_hashicorp_terraform_plugin_framework_types.StringUnknown()
						} else {
							v = github_com_hashicorp_terraform_plugin_framework_types.StringValue(string(a))
						}
						elems[k] = v
					}
					result, resultDiags := github_com_hashicorp_terraform_plugin_framework_types.ListValue(attrType.ElementType(), elems)
					diags.Append(resultDiags...)
					v = result
				}
				attrs["bytes_list"] = v
			}
		}
	}
	{
		var v github_com_hashicorp_terraform_plugin_framework_attr.Value
		existing := attrs["bytes_value"]
		if preserveUnknown && existing != nil && existing.IsUnknown() {
			v = github_com_hashicorp_terraform_plugin_framework_types.StringUnknown()
		} else {
			v = github_com_hashicorp_terraform_plugin_framework_types.StringValue(string(obj.BytesValue))
		}
		attrs["bytes_value"] = v
	}
	{
		attrType, ok := attrType.AttributeTypes()["double_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.double_list"})
		} else {
			attrType, ok := attrType.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.double_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				var v github_com_hashicorp_terraform_plugin_framework_attr.Value
				existing := attrs["double_list"]
				if preserveUnknown && existing != nil && existing.IsUnknown() {
					v = github_com_hashicorp_terraform_plugin_framework_types.ListUnknown(attrType.ElementType())
				} else {
					oldElems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.DoubleList))
					c, ok := existing.(github_com_hashicorp_terraform_plugin_framework_types.List)
					if ok && c.Elements() != nil {
						oldElems = c.Elements()
					}
					elems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.DoubleList))
					copy(elems, oldElems)
					for k, a := range obj.DoubleList {
						var v github_com_hashicorp_terraform_plugin_framework_attr.Value
						existing := elems[k]
						if preserveUnknown && existing != nil && existing.IsUnknown() {
							v = github_com_hashicorp_terraform_plugin_framework_types.Float64Unknown()
						} else {
							v = github_com_hashicorp_terraform_plugin_framework_types.Float64Value(float64(a))
						}
						elems[k] = v
					}
					result, resultDiags := github_com_hashicorp_terraform_plugin_framework_types.ListValue(attrType.ElementType(), elems)
					diags.Append(resultDiags...)
					v = result
				}
				attrs["double_list"] = v
			}
		}
	}
	{
		var v github_com_hashicorp_terraform_plugin_framework_attr.Value
		existing := attrs["double_value"]
		if preserveUnknown && existing != nil && existing.IsUnknown() {
			v = github_com_hashicorp_terraform_plugin_framework_types.Float64Unknown()
		} else {
			v = github_com_hashicorp_terraform_plugin_framework_types.Float64Value(float64(obj.DoubleValue))
		}
		attrs["double_value"] = v
	}
	{
		attrType, ok := attrType.AttributeTypes()["enum_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.enum_list"})
		} else {
			attrType, ok := attrType.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.enum_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				var v github_com_hashicorp_terraform_plugin_framework_attr.Value
				existing := attrs["enum_list"]
				if preserveUnknown && existing != nil && existing.IsUnknown() {
					v = github_com_hashicorp_terraform_plugin_framework_types.ListUnknown(attrType.ElementType())
				} else {
					oldElems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.EnumList))
					c, ok := existing.(github_com_hashicorp_terraform_plugin_framework_types.List)
					if ok && c.Elements() != nil {
						oldElems = c.Elements()
					}
					elems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.EnumList))
					copy(elems, oldElems)
					for k, a := range obj.EnumList {
						var v github_com_hashicorp_terraform_plugin_framework_attr.Value
						existing := elems[k]
						if preserveUnknown && existing != nil && existing.IsUnknown() {
							v = github_com_hashicorp_terraform_plugin_framework_types.Int64Unknown()
						} else {
							v = github_com_hashicorp_terraform_plugin_framework_types.Int64Value(int64(a))
						}
						elems[k] = v
					}
					result, resultDiags := github_com_hashicorp_terraform_plugin_framework_types.ListValue(attrType.ElementType(), elems)
					diags.Append(resultDiags...)
					v = result
				}
				attrs["enum_list"] = v
			}
		}
	}
	{
		var v github_com_hashicorp_terraform_plugin_framework_attr.Value
		existing := attrs["enum_value"]
		if preserveUnknown && existing != nil && existing.IsUnknown() {
			v = github_com_hashicorp_terraform_plugin_framework_types.Int64Unknown()
		} else {
			v = github_com_hashicorp_terraform_plugin_framework_types.Int64Value(int64(obj.EnumValue))
		}
		attrs["enum_value"] = v
	}
	{
		attrType, ok := attrType.AttributeTypes()["float_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.float_list"})
		} else {
			attrType, ok := attrType.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.float_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				var v github_com_hashicorp_terraform_plugin_framework_attr.Value
				existing := attrs["float_list"]
				if preserveUnknown && existing != nil && existing.IsUnknown() {
					v = github_com_hashicorp_terraform_plugin_framework_types.ListUnknown(attrType.ElementType())
				} else {
					oldElems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.FloatList))
					c, ok := existing.(github_com_hashicorp_terraform_plugin_framework_types.List)
					if ok && c.Elements() != nil {
						oldElems = c.Elements()
					}
					elems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.FloatList))
					copy(elems, oldElems)
					for k, a := range obj.FloatList {
						var v github_com_hashicorp_terraform_plugin_framework_attr.Value
						existing := elems[k]
						if preserveUnknown && existing != nil && existing.IsUnknown() {
							v = github_com_hashicorp_terraform_plugin_framework_types.Float64Unknown()
						} else {
							v = github_com_hashicorp_terraform_plugin_framework_types.Float64Value(float64(a))
						}
						elems[k] = v
					}
					result, resultDiags := github_com_hashicorp_terraform_plugin_framework_types.ListValue(attrType.ElementType(), elems)
					diags.Append(resultDiags...)
					v = result
				}
				attrs["float_list"] = v
			}
		}
	}
	{
		var v github_com_hashicorp_terraform_plugin_framework_attr.Value
		existing := attrs["float_value"]
		if preserveUnknown && existing != nil && existing.IsUnknown() {
			v = github_com_hashicorp_terraform_plugin_framework_types.Float64Unknown()
		} else {
			v = github_com_hashicorp_terraform_plugin_framework_types.Float64Value(float64(obj.FloatValue))
		}
		attrs["float_value"] = v
	}
	{
		var v github_com_hashicorp_terraform_plugin_framework_attr.Value
		existing := attrs["id"]
		if preserveUnknown && existing != nil && existing.IsUnknown() {
			v = github_com_hashicorp_terraform_plugin_framework_types.StringUnknown()
		} else {
			v = github_com_hashicorp_terraform_plugin_framework_types.StringValue(string(obj.Id))
		}
		attrs["id"] = v
	}
	{
		attrType, ok := attrType.AttributeTypes()["int32_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.int32_list"})
		} else {
			attrType, ok := attrType.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.int32_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				var v github_com_hashicorp_terraform_plugin_framework_attr.Value
				existing := attrs["int32_list"]
				if preserveUnknown && existing != nil && existing.IsUnknown() {
					v = github_com_hashicorp_terraform_plugin_framework_types.ListUnknown(attrType.ElementType())
				} else {
					oldElems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.Int32List))
					c, ok := existing.(github_com_hashicorp_terraform_plugin_framework_types.List)
					if ok && c.Elements() != nil {
						oldElems = c.Elements()
					}
					elems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.Int32List))
					copy(elems, oldElems)
					for k, a := range obj.Int32List {
						var v github_com_hashicorp_terraform_plugin_framework_attr.Value
						existing := elems[k]
						if preserveUnknown && existing != nil && existing.IsUnknown() {
							v = github_com_hashicorp_terraform_plugin_framework_types.Int64Unknown()
						} else {
							v = github_com_hashicorp_terraform_plugin_framework_types.Int64Value(int64(a))
						}
						elems[k] = v
					}
					result, resultDiags := github_com_hashicorp_terraform_plugin_framework_types.ListValue(attrType.ElementType(), elems)
					diags.Append(resultDiags...)
					v = result
				}
				attrs["int32_list"] = v
			}
		}
	}
	{
		var v github_com_hashicorp_terraform_plugin_framework_attr.Value
		existing := attrs["int32_value"]
		if preserveUnknown && existing != nil && existing.IsUnknown() {
			v = github_com_hashicorp_terraform_plugin_framework_types.Int64Unknown()
		} else {
			v = github_com_hashicorp_terraform_plugin_framework_types.Int64Value(int64(obj.Int32Value))
		}
		attrs["int32_value"] = v
	}
	{
		attrType, ok := attrType.AttributeTypes()["int64_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.int64_list"})
		} else {
			attrType, ok := attrType.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.int64_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				var v github_com_hashicorp_terraform_plugin_framework_attr.Value
				existing := attrs["int64_list"]
				if preserveUnknown && existing != nil && existing.IsUnknown() {
					v = github_com_hashicorp_terraform_plugin_framework_types.ListUnknown(attrType.ElementType())
				} else {
					oldElems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.Int64List))
					c, ok := existing.(github_com_hashicorp_terraform_plugin_framework_types.List)
					if ok && c.Elements() != nil {
						oldElems = c.Elements()
					}
					elems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.Int64List))
					copy(elems, oldElems)
					for k, a := range obj.Int64List {
						var v github_com_hashicorp_terraform_plugin_framework_attr.Value
						existing := elems[k]
						if preserveUnknown && existing != nil && existing.IsUnknown() {
							v = github_com_hashicorp_terraform_plugin_framework_types.Int64Unknown()
						} else {
							v = github_com_hashicorp_terraform_plugin_framework_types.Int64Value(int64(a))
						}
						elems[k] = v
					}
					result, resultDiags := github_com_hashicorp_terraform_plugin_framework_types.ListValue(attrType.ElementType(), elems)
					diags.Append(resultDiags...)
					v = result
				}
				attrs["int64_list"] = v
			}
		}
	}
	{
		var v github_com_hashicorp_terraform_plugin_framework_attr.Value
		existing := attrs["int64_value"]
		if preserveUnknown && existing != nil && existing.IsUnknown() {
			v = github_com_hashicorp_terraform_plugin_framework_types.Int64Unknown()
		} else {
			v = github_com_hashicorp_terraform_plugin_framework_types.Int64Value(int64(obj.Int64Value))
		}
		attrs["int64_value"] = v
	}
	{
		attrType, ok := attrType.AttributeTypes()["string_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Primitives.string_list"})
		} else {
			attrType, ok := attrType.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Primitives.string_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				var v github_com_hashicorp_terraform_plugin_framework_attr.Value
				existing := attrs["string_list"]
				if preserveUnknown && existing != nil && existing.IsUnknown() {
					v = github_com_hashicorp_terraform_plugin_framework_types.ListUnknown(attrType.ElementType())
				} else {
					oldElems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.StringList))
					c, ok := existing.(github_com_hashicorp_terraform_plugin_framework_types.List)
					if ok && c.Elements() != nil {
						oldElems = c.Elements()
					}
					elems := make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.StringList))
					copy(elems, oldElems)
					for k, a := range obj.StringList {
						var v github_com_hashicorp_terraform_plugin_framework_attr.Value
						existing := elems[k]
						if preserveUnknown && existing != nil && existing.IsUnknown() {
							v = github_com_hashicorp_terraform_plugin_framework_types.StringUnknown()
						} else {
							v = github_com_hashicorp_terraform_plugin_framework_types.StringValue(string(a))
						}
						elems[k] = v
					}
					result, resultDiags := github_com_hashicorp_terraform_plugin_framework_types.ListValue(attrType.ElementType(), elems)
					diags.Append(resultDiags...)
					v = result
				}
				attrs["string_list"] = v
			}
		}
	}
	{
		var v github_com_hashicorp_terraform_plugin_framework_attr.Value
		existing := attrs["string_value"]
		if preserveUnknown && existing != nil && existing.IsUnknown() {
			v = github_com_hashicorp_terraform_plugin_framework_types.StringUnknown()
		} else {
			v = github_com_hashicorp_terraform_plugin_framework_types.StringValue(string(obj.StringValue))
		}
		attrs["string_value"] = v
	}
	result, resultDiags := github_com_hashicorp_terraform_plugin_framework_types.ObjectValue(attrType.AttributeTypes(), attrs)
	diags.Append(resultDiags...)
	return result, diags
}

// attrReadMissingDiag represents diagnostic message on an attribute missing in the source object
type attrReadMissingDiag struct {
	Path string
}

func (d attrReadMissingDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrReadMissingDiag) Summary() string {
	return "Error reading from Terraform object"
}

func (d attrReadMissingDiag) Detail() string {
	return fmt.Sprintf("A value for %v is missing in the source Terraform object Attributes", d.Path)
}

func (d attrReadMissingDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrReadConversionFailureDiag represents diagnostic message on a failed type conversion on read
type attrReadConversionFailureDiag struct {
	Path string
	Type string
}

func (d attrReadConversionFailureDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrReadConversionFailureDiag) Summary() string {
	return "Error reading from Terraform object"
}

func (d attrReadConversionFailureDiag) Detail() string {
	return fmt.Sprintf("A value for %v can not be converted to %v", d.Path, d.Type)
}

func (d attrReadConversionFailureDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteMissingDiag represents diagnostic message on an attribute missing in the target object
type attrWriteMissingDiag struct {
	Path string
}

func (d attrWriteMissingDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteMissingDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteMissingDiag) Detail() string {
	return fmt.Sprintf("A value for %v is missing in the source Terraform object AttributeTypes", d.Path)
}

func (d attrWriteMissingDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteConversionFailureDiag represents diagnostic message on a failed type conversion on write
type attrWriteConversionFailureDiag struct {
	Path string
	Type string
}

func (d attrWriteConversionFailureDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteConversionFailureDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteConversionFailureDiag) Detail() string {
	return fmt.Sprintf("A value for %v can not be converted to %v", d.Path, d.Type)
}

func (d attrWriteConversionFailureDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteGeneralError represents diagnostic message on a generic error on write
type attrWriteGeneralError struct {
	Path string
	Err  error
}

func (d attrWriteGeneralError) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteGeneralError) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteGeneralError) Detail() string {
	return fmt.Sprintf("%s: %s", d.Path, d.Err.Error())
}

func (d attrWriteGeneralError) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteUnexpectedExistingTypeDiag represents diagnostic message when a field is initialized with a value whose go
// type does not match what we'd expect.
type attrWriteUnexpectedExistingTypeDiag struct {
	Path string
	Type string
}

func (d attrWriteUnexpectedExistingTypeDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteUnexpectedExistingTypeDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteUnexpectedExistingTypeDiag) Detail() string {
	return fmt.Sprintf("A value for %v is already initialized and its type is not %v", d.Path, d.Type)
}

func (d attrWriteUnexpectedExistingTypeDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}
