/*
Copyright 2015-2022 Gravitational, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: custom.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gravitational_protoc_gen_terraform_v3_examples_types "github.com/gravitational/protoc-gen-terraform/v3/examples/types"
	github_com_hashicorp_terraform_plugin_framework_attr "github.com/hashicorp/terraform-plugin-framework/attr"
	github_com_hashicorp_terraform_plugin_framework_diag "github.com/hashicorp/terraform-plugin-framework/diag"
	github_com_hashicorp_terraform_plugin_framework_tfsdk "github.com/hashicorp/terraform-plugin-framework/tfsdk"
	github_com_hashicorp_terraform_plugin_framework_types "github.com/hashicorp/terraform-plugin-framework/types"
	github_com_hashicorp_terraform_plugin_go_tftypes "github.com/hashicorp/terraform-plugin-go/tftypes"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// GenSchemaCustom returns tfsdk.Schema definition for Custom
func GenSchemaCustom(ctx context.Context) (github_com_hashicorp_terraform_plugin_framework_tfsdk.Schema, github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics) {
	return github_com_hashicorp_terraform_plugin_framework_tfsdk.Schema{Attributes: map[string]github_com_hashicorp_terraform_plugin_framework_tfsdk.Attribute{
		"bool_custom": GenSchemaBoolSpecial(ctx, github_com_hashicorp_terraform_plugin_framework_tfsdk.Attribute{
			Description: "bool_custom custom bool field.",
			Optional:    true,
		}),
		"bool_custom_list": GenSchemaBoolSpecialList(ctx, github_com_hashicorp_terraform_plugin_framework_tfsdk.Attribute{
			Description: "bool_custom_list custom bool list field.",
			Optional:    true,
		}),
		"computed": {
			Computed:      true,
			Description:   "computed is a computed field.",
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_tfsdk.UseStateForUnknown()},
			Type:          github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
		"custom_name_override": {
			Description: "name_override is a field with a name override.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
		"id": {
			Computed:      true,
			Description:   "",
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_tfsdk.UseStateForUnknown()},
			Type:          github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
		"injected": {
			Computed: true,
			Optional: false,
			Required: false,
			Type:     github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
		"plan_modifier": {
			Computed:      true,
			Description:   "plan_modifier is a field with a plan modifier.",
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{UseMockPlanModifier()},
			Type:          github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
		"required": {
			Description: "required is a required field.",
			Required:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
		"schema_override": {
			Description: "",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
		"sensitive": {
			Description: "sensitive is a sensitive field.",
			Optional:    true,
			Sensitive:   true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
		"string_override": GenSchemaStringCustom(ctx, github_com_hashicorp_terraform_plugin_framework_tfsdk.Attribute{
			Description: "string_override is represented by a single string in the go struct, but by a list of strings in the Terraform Schema. The plugin's configuration specifies a custom_type (StringCustom), the generator should use the functions \"GenSchemaStringCustom\", \"CopyFromStringCustom\", \"CopyToStringCustom\" instead of attempting to generate them.",
			Optional:    true,
		}),
		"validated": {
			Description: "validated is a validated field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.StringType,
			Validators:  []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributeValidator{UseMockValidator()},
		},
	}}, nil
}

// CopyCustomFromTerraform copies contents of the source Terraform object into a target struct
func CopyCustomFromTerraform(_ context.Context, tf github_com_hashicorp_terraform_plugin_framework_types.Object, obj *github_com_gravitational_protoc_gen_terraform_v3_examples_types.Custom) github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics {
	var diags github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics
	{
		a, ok := tf.Attrs["bool_custom"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Custom.bool_custom"})
		}
		CopyFromBoolSpecial(diags, a, &obj.BoolCustom)
	}
	{
		a, ok := tf.Attrs["bool_custom_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Custom.bool_custom_list"})
		}
		CopyFromBoolSpecialList(diags, a, &obj.BoolCustomList)
	}
	{
		a, ok := tf.Attrs["computed"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Custom.computed"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Custom.computed", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.Null && !v.Unknown {
					t = string(v.Value)
				}
				obj.Computed = t
			}
		}
	}
	{
		a, ok := tf.Attrs["id"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Custom.id"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Custom.id", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.Null && !v.Unknown {
					t = string(v.Value)
				}
				obj.Id = t
			}
		}
	}
	{
		a, ok := tf.Attrs["custom_name_override"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Custom.name_override"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Custom.name_override", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.Null && !v.Unknown {
					t = string(v.Value)
				}
				obj.NameOverride = t
			}
		}
	}
	{
		a, ok := tf.Attrs["plan_modifier"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Custom.plan_modifier"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Custom.plan_modifier", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.Null && !v.Unknown {
					t = string(v.Value)
				}
				obj.PlanModifier = t
			}
		}
	}
	{
		a, ok := tf.Attrs["required"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Custom.required"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Custom.required", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.Null && !v.Unknown {
					t = string(v.Value)
				}
				obj.Required = t
			}
		}
	}
	{
		a, ok := tf.Attrs["schema_override"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Custom.schema_override"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Custom.schema_override", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t OverrideCastType
				if !v.Null && !v.Unknown {
					t = OverrideCastType(v.Value)
				}
				obj.SchemaOverride = t
			}
		}
	}
	{
		a, ok := tf.Attrs["sensitive"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Custom.sensitive"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Custom.sensitive", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.Null && !v.Unknown {
					t = string(v.Value)
				}
				obj.Sensitive = t
			}
		}
	}
	{
		a, ok := tf.Attrs["string_override"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Custom.string_override"})
		}
		CopyFromStringCustom(diags, a, &obj.StringOverride)
	}
	{
		a, ok := tf.Attrs["validated"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Custom.validated"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Custom.validated", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.Null && !v.Unknown {
					t = string(v.Value)
				}
				obj.Validated = t
			}
		}
	}
	return diags
}

// CopyCustomToTerraform copies contents of the source Terraform object into a target struct
func CopyCustomToTerraform(ctx context.Context, obj *github_com_gravitational_protoc_gen_terraform_v3_examples_types.Custom, tf *github_com_hashicorp_terraform_plugin_framework_types.Object) github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics {
	var diags github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics
	tf.Null = false
	tf.Unknown = false
	if tf.Attrs == nil {
		tf.Attrs = make(map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value)
	}
	{
		t, ok := tf.AttrTypes["bool_custom"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Custom.bool_custom"})
		} else {
			v := CopyToBoolSpecial(diags, obj.BoolCustom, t, tf.Attrs["bool_custom"])
			tf.Attrs["bool_custom"] = v
		}
	}
	{
		t, ok := tf.AttrTypes["bool_custom_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Custom.bool_custom_list"})
		} else {
			v := CopyToBoolSpecialList(diags, obj.BoolCustomList, t, tf.Attrs["bool_custom_list"])
			tf.Attrs["bool_custom_list"] = v
		}
	}
	{
		t, ok := tf.AttrTypes["computed"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Custom.computed"})
		} else {
			v, ok := tf.Attrs["computed"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				if tf.Attrs["computed"] != nil {
					diags.Append(attrWriteUnexpectedExistingTypeDiag{"Custom.computed", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Custom.computed", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Custom.computed", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = string(obj.Computed) == ""
			}
			v.Value = string(obj.Computed)
			v.Unknown = false
			tf.Attrs["computed"] = v
		}
	}
	{
		t, ok := tf.AttrTypes["id"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Custom.id"})
		} else {
			v, ok := tf.Attrs["id"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				if tf.Attrs["id"] != nil {
					diags.Append(attrWriteUnexpectedExistingTypeDiag{"Custom.id", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Custom.id", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Custom.id", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = string(obj.Id) == ""
			}
			v.Value = string(obj.Id)
			v.Unknown = false
			tf.Attrs["id"] = v
		}
	}
	{
		t, ok := tf.AttrTypes["custom_name_override"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Custom.name_override"})
		} else {
			v, ok := tf.Attrs["custom_name_override"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				if tf.Attrs["custom_name_override"] != nil {
					diags.Append(attrWriteUnexpectedExistingTypeDiag{"Custom.name_override", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Custom.name_override", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Custom.name_override", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = string(obj.NameOverride) == ""
			}
			v.Value = string(obj.NameOverride)
			v.Unknown = false
			tf.Attrs["custom_name_override"] = v
		}
	}
	{
		t, ok := tf.AttrTypes["plan_modifier"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Custom.plan_modifier"})
		} else {
			v, ok := tf.Attrs["plan_modifier"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				if tf.Attrs["plan_modifier"] != nil {
					diags.Append(attrWriteUnexpectedExistingTypeDiag{"Custom.plan_modifier", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Custom.plan_modifier", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Custom.plan_modifier", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = string(obj.PlanModifier) == ""
			}
			v.Value = string(obj.PlanModifier)
			v.Unknown = false
			tf.Attrs["plan_modifier"] = v
		}
	}
	{
		t, ok := tf.AttrTypes["required"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Custom.required"})
		} else {
			v, ok := tf.Attrs["required"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				if tf.Attrs["required"] != nil {
					diags.Append(attrWriteUnexpectedExistingTypeDiag{"Custom.required", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Custom.required", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Custom.required", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = string(obj.Required) == ""
			}
			v.Value = string(obj.Required)
			v.Unknown = false
			tf.Attrs["required"] = v
		}
	}
	{
		t, ok := tf.AttrTypes["schema_override"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Custom.schema_override"})
		} else {
			v, ok := tf.Attrs["schema_override"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				if tf.Attrs["schema_override"] != nil {
					diags.Append(attrWriteUnexpectedExistingTypeDiag{"Custom.schema_override", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Custom.schema_override", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Custom.schema_override", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = string(obj.SchemaOverride) == ""
			}
			v.Value = string(obj.SchemaOverride)
			v.Unknown = false
			tf.Attrs["schema_override"] = v
		}
	}
	{
		t, ok := tf.AttrTypes["sensitive"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Custom.sensitive"})
		} else {
			v, ok := tf.Attrs["sensitive"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				if tf.Attrs["sensitive"] != nil {
					diags.Append(attrWriteUnexpectedExistingTypeDiag{"Custom.sensitive", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Custom.sensitive", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Custom.sensitive", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = string(obj.Sensitive) == ""
			}
			v.Value = string(obj.Sensitive)
			v.Unknown = false
			tf.Attrs["sensitive"] = v
		}
	}
	{
		t, ok := tf.AttrTypes["string_override"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Custom.string_override"})
		} else {
			v := CopyToStringCustom(diags, obj.StringOverride, t, tf.Attrs["string_override"])
			tf.Attrs["string_override"] = v
		}
	}
	{
		t, ok := tf.AttrTypes["validated"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Custom.validated"})
		} else {
			v, ok := tf.Attrs["validated"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				if tf.Attrs["validated"] != nil {
					diags.Append(attrWriteUnexpectedExistingTypeDiag{"Custom.validated", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Custom.validated", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Custom.validated", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = string(obj.Validated) == ""
			}
			v.Value = string(obj.Validated)
			v.Unknown = false
			tf.Attrs["validated"] = v
		}
	}
	return diags
}

// attrReadMissingDiag represents diagnostic message on an attribute missing in the source object
type attrReadMissingDiag struct {
	Path string
}

func (d attrReadMissingDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrReadMissingDiag) Summary() string {
	return "Error reading from Terraform object"
}

func (d attrReadMissingDiag) Detail() string {
	return fmt.Sprintf("A value for %v is missing in the source Terraform object Attrs", d.Path)
}

func (d attrReadMissingDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrReadConversionFailureDiag represents diagnostic message on a failed type conversion on read
type attrReadConversionFailureDiag struct {
	Path string
	Type string
}

func (d attrReadConversionFailureDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrReadConversionFailureDiag) Summary() string {
	return "Error reading from Terraform object"
}

func (d attrReadConversionFailureDiag) Detail() string {
	return fmt.Sprintf("A value for %v can not be converted to %v", d.Path, d.Type)
}

func (d attrReadConversionFailureDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteMissingDiag represents diagnostic message on an attribute missing in the target object
type attrWriteMissingDiag struct {
	Path string
}

func (d attrWriteMissingDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteMissingDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteMissingDiag) Detail() string {
	return fmt.Sprintf("A value for %v is missing in the source Terraform object AttrTypes", d.Path)
}

func (d attrWriteMissingDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteConversionFailureDiag represents diagnostic message on a failed type conversion on write
type attrWriteConversionFailureDiag struct {
	Path string
	Type string
}

func (d attrWriteConversionFailureDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteConversionFailureDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteConversionFailureDiag) Detail() string {
	return fmt.Sprintf("A value for %v can not be converted to %v", d.Path, d.Type)
}

func (d attrWriteConversionFailureDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteGeneralError represents diagnostic message on a generic error on write
type attrWriteGeneralError struct {
	Path string
	Err  error
}

func (d attrWriteGeneralError) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteGeneralError) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteGeneralError) Detail() string {
	return fmt.Sprintf("%s: %s", d.Path, d.Err.Error())
}

func (d attrWriteGeneralError) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteUnexpectedExistingTypeDiag represents diagnostic message when a field is initialized with a value whose go
// type does not match what we'd expect.
type attrWriteUnexpectedExistingTypeDiag struct {
	Path string
	Type string
}

func (d attrWriteUnexpectedExistingTypeDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteUnexpectedExistingTypeDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteUnexpectedExistingTypeDiag) Detail() string {
	return fmt.Sprintf("A value for %v is already initialized and its type is not %v", d.Path, d.Type)
}

func (d attrWriteUnexpectedExistingTypeDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}
