---
target_package_name: v1
default_package_name: "github.com/gravitational/protoc-gen-terraform/v5/examples/types"
use_state_for_unknown_by_default: true
sort: true

types:
  - Custom

injected_fields:
  Custom:
    - name: injected
      type: github.com/hashicorp/terraform-plugin-framework/types.StringType
      computed: true
      default_value_method: github.com/hashicorp/terraform-plugin-framework/types.StringNull
      plan_modifiers:
        - "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier.UseStateForUnknown()"

computed_fields:
  - Custom.id
  - Custom.computed
  - Custom.plan_modifier

exclude_fields:
  - Custom.excluded

required_fields:
  - Custom.required

sensitive_fields:
  - Custom.sensitive

name_overrides:
  Custom.name_override: "custom_name_override"

suffixes:
  BoolCustom: BoolSpecial
  BoolCustomList: BoolSpecialList

validators:
  "Custom.validated":
    - UseMockValidator()

plan_modifiers:
  "Custom.plan_modifier":
    - UseMockPlanModifier()

custom_types:
  "Custom.string_override": StringCustom

schema_types:
  "Custom.string_override":
    type: "github.com/hashicorp/terraform-plugin-framework/types.ListType"
    value_type: "github.com/hashicorp/terraform-plugin-framework/types.List"
    value_from_method: "Elements"
    value_to_method: "github.com/hashicorp/terraform-plugin-framework/types.ListValue"
    null_value_method: "github.com/hashicorp/terraform-plugin-framework/types.ListNull"
    unknown_value_method: "github.com/hashicorp/terraform-plugin-framework/types.ListUnknown"
    cast_to_type: "[]string"
    cast_from_type: "string"
  "Custom.schema_override":
    type: "github.com/hashicorp/terraform-plugin-framework/types.StringType"
    value_type: "github.com/hashicorp/terraform-plugin-framework/types.String"
    value_from_method: "ValueString"
    value_to_method: "github.com/hashicorp/terraform-plugin-framework/types.StringValue"
    null_value_method: "github.com/hashicorp/terraform-plugin-framework/types.StringNull"
    unknown_value_method: "github.com/hashicorp/terraform-plugin-framework/types.StringUnknown"
    cast_to_type: "string"
    cast_from_type: "OverrideCastType"
