---
target_package_name: v1
default_package_name: "github.com/gravitational/protoc-gen-terraform/v3/examples/types"
use_state_for_unknown_by_default: true
sort: true

types:
  - Custom

injected_fields:
  Custom:
    - name: injected
      type: github.com/hashicorp/terraform-plugin-framework/types.StringType
      computed: true

computed_fields:
  - Custom.id
  - Custom.computed
  - Custom.sensitive
  - Custom.validated
  - Custom.name_override
  - Custom.plan_modifier
  - Custom.bool_custom
  - Custom.bool_custom_list
  - Custom.string_override
  - Custom.schema_override

exclude_fields:
  - Custom.excluded

required_fields:
  - Custom.required

sensitive_fields:
  - Custom.sensitive

name_overrides:
  Custom.name_override: "custom_name_override"

suffixes:
  BoolCustom: BoolSpecial
  BoolCustomList: BoolSpecialList

custom_types:
  "Custom.string_override": StringCustom

validators:
  "Custom.validated":
    - UseMockValidator()

plan_modifiers:
  "Custom.plan_modifier":
    - UseMockPlanModifier()

schema_types:
  "Custom.schema_override":
    type: "github.com/hashicorp/terraform-plugin-framework/types.StringType"
    value_type: "github.com/hashicorp/terraform-plugin-framework/types.String"
    cast_to_type: "string"
    cast_from_type: "OverrideCastType"
