---
target_package_name: v1
default_package_name: "github.com/gravitational/protoc-gen-terraform/v3/examples/types"
use_state_for_unknown_by_default: true
sort: true

types:
  - Objects

computed_fields:
  - Objects.id
  - Primitives.id
  - Primitives.bytes_value
  - Primitives.int64_value
  - Primitives.double_value
  - Primitives.optional_string
  - Leaf.value
