---
target_package_name: v1
default_package_name: "github.com/gravitational/protoc-gen-terraform/v3/examples/types"
sort: true

types:
  - Objects

computed_fields:
  - Objects.id

# Apply `UseStateForUnknown` for attribute values that should remain the same
# after a resource update.
plan_modifiers:
  "Objects.id":
    - github.com/hashicorp/terraform-plugin-framework/tfsdk.UseStateForUnknown()
