---
target_package_name: v1
default_package_name: "github.com/gravitational/protoc-gen-terraform/v3/examples/types"
use_state_for_unknown_by_default: true
sort: true

types:
  - Primitives

computed_fields:
  - Primitives.id
  - Primitives.string_value
  - Primitives.int32_value
  - Primitives.int64_value
  - Primitives.float_value
  - Primitives.double_value
  - Primitives.bool_value
  - Primitives.bytes_value
  - Primitives.enum_value
  - Primitives.string_list
  - Primitives.int32_list
  - Primitives.int64_list
  - Primitives.float_list
  - Primitives.double_list
  - Primitives.bool_list
  - Primitives.bytes_list
  - Primitives.enum_list
