// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: objects.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Objects contains examples of nested object and map protobuf field types.
type Objects struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// primitives field.
	Primitives Primitives `protobuf:"bytes,2,opt,name=primitives,proto3" json:"primitives"`
	// string_map map of strings.
	StringMap map[string]string `protobuf:"bytes,3,rep,name=string_map,json=stringMap,proto3" json:"string_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// int_map map of ints.
	IntMap map[string]int64 `protobuf:"bytes,4,rep,name=int_map,json=intMap,proto3" json:"int_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// bool_map map of bools.
	BoolMap map[string]bool `protobuf:"bytes,5,rep,name=bool_map,json=boolMap,proto3" json:"bool_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// nested_value is a nested object.
	NestedValue Nested `protobuf:"bytes,6,opt,name=nested_value,json=nestedValue,proto3" json:"nested_value"`
	// nested_nullable is a nullable nested object.
	NestedNullable *Nested `protobuf:"bytes,7,opt,name=nested_nullable,json=nestedNullable,proto3" json:"nested_nullable,omitempty"`
	// nested_list is a list of nested objects.
	NestedList []Nested `protobuf:"bytes,8,rep,name=nested_list,json=nestedList,proto3" json:"nested_list"`
	// nested_nullable_list is a nullable list of nested objects.
	NestedNullableList []*Nested `protobuf:"bytes,9,rep,name=nested_nullable_list,json=nestedNullableList,proto3" json:"nested_nullable_list,omitempty"`
	// nested_map is a map of nested objects.
	NestedMap map[string]Nested `protobuf:"bytes,10,rep,name=nested_map,json=nestedMap,proto3" json:"nested_map" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// nested_map is a nullable map of nested objects.
	NestedNullableMap map[string]*Nested `protobuf:"bytes,11,rep,name=nested_nullable_map,json=nestedNullableMap,proto3" json:"nested_nullable_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// empty is an empty field.
	Empty *Empty `protobuf:"bytes,12,opt,name=empty,proto3" json:"empty,omitempty"`
	// embeded is an embedded field.
	Nested `protobuf:"bytes,13,opt,name=embedded,proto3,embedded=embedded" json:"embedded"`
	// embedded_nullable is an embedded nullable field.
	*LeafEmbedded `protobuf:"bytes,14,opt,name=embedded_nullable,json=embeddedNullable,proto3,embedded=embedded_nullable" json:"embedded_nullable,omitempty"`
	// one_of_objects is a oneof objects field.
	//
	// Types that are valid to be assigned to OneOfObjects:
	//
	//	*Objects_Branch1
	//	*Objects_Branch2
	OneOfObjects isObjects_OneOfObjects `protobuf_oneof:"one_of_objects"`
	// one_of_primitives is a oneof primitives field.
	//
	// Types that are valid to be assigned to OneOfPrimitives:
	//
	//	*Objects_BranchBool
	//	*Objects_BranchString
	//	*Objects_BranchInt
	OneOfPrimitives      isObjects_OneOfPrimitives `protobuf_oneof:"one_of_primitives"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Objects) Reset()         { *m = Objects{} }
func (m *Objects) String() string { return proto.CompactTextString(m) }
func (*Objects) ProtoMessage()    {}
func (*Objects) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{0}
}
func (m *Objects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Objects.Unmarshal(m, b)
}
func (m *Objects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Objects.Marshal(b, m, deterministic)
}
func (m *Objects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Objects.Merge(m, src)
}
func (m *Objects) XXX_Size() int {
	return xxx_messageInfo_Objects.Size(m)
}
func (m *Objects) XXX_DiscardUnknown() {
	xxx_messageInfo_Objects.DiscardUnknown(m)
}

var xxx_messageInfo_Objects proto.InternalMessageInfo

type isObjects_OneOfObjects interface {
	isObjects_OneOfObjects()
}
type isObjects_OneOfPrimitives interface {
	isObjects_OneOfPrimitives()
}

type Objects_Branch1 struct {
	Branch1 *Nested `protobuf:"bytes,15,opt,name=branch1,proto3,oneof" json:"branch1,omitempty"`
}
type Objects_Branch2 struct {
	Branch2 *Nested `protobuf:"bytes,16,opt,name=branch2,proto3,oneof" json:"branch2,omitempty"`
}
type Objects_BranchBool struct {
	BranchBool bool `protobuf:"varint,17,opt,name=branch_bool,json=branchBool,proto3,oneof" json:"branch_bool,omitempty"`
}
type Objects_BranchString struct {
	BranchString string `protobuf:"bytes,18,opt,name=branch_string,json=branchString,proto3,oneof" json:"branch_string,omitempty"`
}
type Objects_BranchInt struct {
	BranchInt int64 `protobuf:"varint,19,opt,name=branch_int,json=branchInt,proto3,oneof" json:"branch_int,omitempty"`
}

func (*Objects_Branch1) isObjects_OneOfObjects()         {}
func (*Objects_Branch2) isObjects_OneOfObjects()         {}
func (*Objects_BranchBool) isObjects_OneOfPrimitives()   {}
func (*Objects_BranchString) isObjects_OneOfPrimitives() {}
func (*Objects_BranchInt) isObjects_OneOfPrimitives()    {}

func (m *Objects) GetOneOfObjects() isObjects_OneOfObjects {
	if m != nil {
		return m.OneOfObjects
	}
	return nil
}
func (m *Objects) GetOneOfPrimitives() isObjects_OneOfPrimitives {
	if m != nil {
		return m.OneOfPrimitives
	}
	return nil
}

func (m *Objects) GetBranch1() *Nested {
	if x, ok := m.GetOneOfObjects().(*Objects_Branch1); ok {
		return x.Branch1
	}
	return nil
}

func (m *Objects) GetBranch2() *Nested {
	if x, ok := m.GetOneOfObjects().(*Objects_Branch2); ok {
		return x.Branch2
	}
	return nil
}

func (m *Objects) GetBranchBool() bool {
	if x, ok := m.GetOneOfPrimitives().(*Objects_BranchBool); ok {
		return x.BranchBool
	}
	return false
}

func (m *Objects) GetBranchString() string {
	if x, ok := m.GetOneOfPrimitives().(*Objects_BranchString); ok {
		return x.BranchString
	}
	return ""
}

func (m *Objects) GetBranchInt() int64 {
	if x, ok := m.GetOneOfPrimitives().(*Objects_BranchInt); ok {
		return x.BranchInt
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Objects) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Objects_Branch1)(nil),
		(*Objects_Branch2)(nil),
		(*Objects_BranchBool)(nil),
		(*Objects_BranchString)(nil),
		(*Objects_BranchInt)(nil),
	}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{1}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Nested struct {
	Leaf                 Leaf     `protobuf:"bytes,1,opt,name=leaf,proto3" json:"leaf"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nested) Reset()         { *m = Nested{} }
func (m *Nested) String() string { return proto.CompactTextString(m) }
func (*Nested) ProtoMessage()    {}
func (*Nested) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{2}
}
func (m *Nested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nested.Unmarshal(m, b)
}
func (m *Nested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nested.Marshal(b, m, deterministic)
}
func (m *Nested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nested.Merge(m, src)
}
func (m *Nested) XXX_Size() int {
	return xxx_messageInfo_Nested.Size(m)
}
func (m *Nested) XXX_DiscardUnknown() {
	xxx_messageInfo_Nested.DiscardUnknown(m)
}

var xxx_messageInfo_Nested proto.InternalMessageInfo

type Leaf struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Leaf) Reset()         { *m = Leaf{} }
func (m *Leaf) String() string { return proto.CompactTextString(m) }
func (*Leaf) ProtoMessage()    {}
func (*Leaf) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{3}
}
func (m *Leaf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Leaf.Unmarshal(m, b)
}
func (m *Leaf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Leaf.Marshal(b, m, deterministic)
}
func (m *Leaf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Leaf.Merge(m, src)
}
func (m *Leaf) XXX_Size() int {
	return xxx_messageInfo_Leaf.Size(m)
}
func (m *Leaf) XXX_DiscardUnknown() {
	xxx_messageInfo_Leaf.DiscardUnknown(m)
}

var xxx_messageInfo_Leaf proto.InternalMessageInfo

type LeafEmbedded struct {
	EmbeddedValue        string   `protobuf:"bytes,1,opt,name=embedded_value,json=embeddedValue,proto3" json:"embedded_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeafEmbedded) Reset()         { *m = LeafEmbedded{} }
func (m *LeafEmbedded) String() string { return proto.CompactTextString(m) }
func (*LeafEmbedded) ProtoMessage()    {}
func (*LeafEmbedded) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{4}
}
func (m *LeafEmbedded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeafEmbedded.Unmarshal(m, b)
}
func (m *LeafEmbedded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeafEmbedded.Marshal(b, m, deterministic)
}
func (m *LeafEmbedded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeafEmbedded.Merge(m, src)
}
func (m *LeafEmbedded) XXX_Size() int {
	return xxx_messageInfo_LeafEmbedded.Size(m)
}
func (m *LeafEmbedded) XXX_DiscardUnknown() {
	xxx_messageInfo_LeafEmbedded.DiscardUnknown(m)
}

var xxx_messageInfo_LeafEmbedded proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Objects)(nil), "types.Objects")
	proto.RegisterMapType((map[string]bool)(nil), "types.Objects.BoolMapEntry")
	proto.RegisterMapType((map[string]int64)(nil), "types.Objects.IntMapEntry")
	proto.RegisterMapType((map[string]Nested)(nil), "types.Objects.NestedMapEntry")
	proto.RegisterMapType((map[string]*Nested)(nil), "types.Objects.NestedNullableMapEntry")
	proto.RegisterMapType((map[string]string)(nil), "types.Objects.StringMapEntry")
	proto.RegisterType((*Empty)(nil), "types.Empty")
	proto.RegisterType((*Nested)(nil), "types.Nested")
	proto.RegisterType((*Leaf)(nil), "types.Leaf")
	proto.RegisterType((*LeafEmbedded)(nil), "types.LeafEmbedded")
}

func init() { proto.RegisterFile("objects.proto", fileDescriptor_7da965bc36916fc1) }

var fileDescriptor_7da965bc36916fc1 = []byte{
	// 673 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0x4f, 0x6f, 0xda, 0x4c,
	0x10, 0xc6, 0x59, 0xfe, 0x33, 0x36, 0x0e, 0x2c, 0xd1, 0xab, 0x15, 0x6f, 0x9b, 0x50, 0x2a, 0x24,
	0x7a, 0x21, 0x2a, 0x69, 0xd3, 0x36, 0xca, 0x09, 0x09, 0x89, 0xb4, 0x69, 0x5a, 0x39, 0x52, 0x2f,
	0x3d, 0x58, 0x76, 0xd8, 0xa4, 0x6e, 0x8d, 0x8d, 0xf0, 0x26, 0x12, 0xdf, 0x90, 0x63, 0x3e, 0x41,
	0xa5, 0xe6, 0x3b, 0xf4, 0x5e, 0x79, 0x76, 0x0d, 0xc6, 0x72, 0x9a, 0x43, 0x6f, 0xde, 0x99, 0xe7,
	0xf7, 0xcc, 0xb2, 0x3b, 0xb3, 0x40, 0x3d, 0x70, 0xbe, 0xf3, 0x4b, 0x11, 0x0e, 0xe6, 0x8b, 0x40,
	0x04, 0xb4, 0x24, 0x96, 0x73, 0x1e, 0xb6, 0x77, 0xaf, 0x83, 0xeb, 0x00, 0x23, 0x07, 0xd1, 0x97,
	0x4c, 0xb6, 0x1b, 0xf3, 0x85, 0x3b, 0x73, 0x85, 0x7b, 0xcb, 0x95, 0xbc, 0xfb, 0x1b, 0xa0, 0xf2,
	0x49, 0x1a, 0x50, 0x03, 0xf2, 0xee, 0x94, 0x91, 0x0e, 0xe9, 0xd7, 0xcc, 0xbc, 0x3b, 0xa5, 0x6f,
	0x00, 0x36, 0x7a, 0x96, 0xef, 0x90, 0xbe, 0x36, 0x6c, 0x0e, 0xd0, 0x7f, 0xf0, 0x79, 0x9d, 0x18,
	0x15, 0x57, 0x3f, 0xf7, 0x73, 0x66, 0x42, 0x4a, 0x4f, 0x00, 0x42, 0xb1, 0x70, 0xfd, 0x6b, 0x6b,
	0x66, 0xcf, 0x59, 0xa1, 0x53, 0xe8, 0x6b, 0xc3, 0xa7, 0x0a, 0x54, 0xc5, 0x06, 0x17, 0x28, 0xf8,
	0x68, 0xcf, 0xc7, 0xbe, 0x58, 0x2c, 0xcd, 0x5a, 0x18, 0xaf, 0xe9, 0x21, 0x54, 0x5c, 0x5f, 0x20,
	0x5a, 0x44, 0xb4, 0x9d, 0x42, 0x4f, 0x7d, 0xb1, 0xe6, 0xca, 0x2e, 0x2e, 0xe8, 0x11, 0x54, 0x9d,
	0x20, 0xf0, 0x90, 0x2a, 0x21, 0xf5, 0x7f, 0x8a, 0x1a, 0x05, 0x81, 0xb7, 0xc6, 0x2a, 0x8e, 0x5c,
	0xd1, 0x23, 0xd0, 0x7d, 0x1e, 0x0a, 0x3e, 0xb5, 0x6e, 0x6d, 0xef, 0x86, 0xb3, 0x32, 0xfe, 0xca,
	0xba, 0x62, 0xcf, 0x31, 0xa5, 0x7e, 0xa1, 0x26, 0x85, 0x5f, 0x22, 0x1d, 0x3d, 0x81, 0x1d, 0xc5,
	0xf9, 0x37, 0x9e, 0x67, 0x3b, 0x1e, 0x67, 0x95, 0x87, 0x50, 0x62, 0x1a, 0x52, 0x7b, 0xae, 0xa4,
	0xf4, 0x15, 0x28, 0x33, 0xcb, 0x73, 0x43, 0xc1, 0xaa, 0xb8, 0xe1, 0xcc, 0xa2, 0x20, 0x75, 0x67,
	0x6e, 0x28, 0xe8, 0x18, 0x76, 0x53, 0x35, 0x25, 0x5e, 0x7b, 0x08, 0x27, 0x26, 0xdd, 0x2e, 0x8c,
	0x36, 0x23, 0x50, 0xa6, 0x78, 0x58, 0x90, 0x79, 0x3b, 0xd2, 0x24, 0x3e, 0x2e, 0xb5, 0x97, 0x9a,
	0x1f, 0x47, 0xe9, 0x57, 0x68, 0xa5, 0xb7, 0x12, 0x99, 0x69, 0x68, 0xd6, 0xcb, 0x34, 0x8b, 0xf7,
	0xb0, 0x65, 0x4a, 0xcc, 0xa6, 0x9f, 0xce, 0xd2, 0x2e, 0x94, 0xf8, 0x6c, 0x2e, 0x96, 0x4c, 0xc7,
	0x13, 0xd5, 0x95, 0xdd, 0x38, 0x8a, 0x99, 0x32, 0x45, 0x0f, 0xa1, 0xca, 0x67, 0x0e, 0x9f, 0x4e,
	0xf9, 0x94, 0xd5, 0xb3, 0x0e, 0xbe, 0x1a, 0x6d, 0xf9, 0x2e, 0xaa, 0xb0, 0x16, 0xd2, 0xf7, 0xd0,
	0x8c, 0xbf, 0x37, 0xd7, 0x66, 0x20, 0xdd, 0x52, 0xf4, 0x19, 0xb7, 0xaf, 0xc6, 0x4a, 0x83, 0x1e,
	0x04, 0x3d, 0x1a, 0x31, 0xb7, 0xbe, 0xc2, 0x17, 0x50, 0x71, 0x16, 0xb6, 0x7f, 0xf9, 0xed, 0x25,
	0xdb, 0xc9, 0xa8, 0x3f, 0xc9, 0x99, 0x71, 0x7e, 0x23, 0x1d, 0xb2, 0xc6, 0x5f, 0xa5, 0x43, 0xfa,
	0x0c, 0x34, 0xf9, 0x69, 0x45, 0x0d, 0xca, 0x9a, 0x1d, 0xd2, 0xaf, 0x4e, 0x88, 0x09, 0x32, 0x18,
	0xb5, 0x30, 0xed, 0x41, 0x5d, 0x49, 0xe4, 0xc8, 0x30, 0x1a, 0x0d, 0xec, 0x84, 0x98, 0xba, 0x0c,
	0xcb, 0xc1, 0xa2, 0xfb, 0xa0, 0x20, 0xcb, 0xf5, 0x05, 0x6b, 0x75, 0x48, 0xbf, 0x30, 0x21, 0x66,
	0x4d, 0xc6, 0x4e, 0x7d, 0xd1, 0x3e, 0x01, 0x63, 0x7b, 0x06, 0x69, 0x03, 0x0a, 0x3f, 0xf8, 0x52,
	0x3d, 0x00, 0xd1, 0x27, 0xdd, 0x85, 0x92, 0x1c, 0x8b, 0x3c, 0xc6, 0xe4, 0xe2, 0x38, 0xff, 0x96,
	0xb4, 0xdf, 0x81, 0x96, 0x18, 0xc3, 0xc7, 0xd0, 0x42, 0x12, 0x3d, 0x06, 0x3d, 0x39, 0x8b, 0x8f,
	0xb1, 0xd5, 0x24, 0xfb, 0x01, 0x8c, 0xed, 0xd6, 0xcc, 0xa0, 0x9f, 0x27, 0xe9, 0xf4, 0x61, 0x27,
	0xcd, 0x2e, 0xe0, 0xbf, 0xec, 0xd6, 0xfc, 0x07, 0xd3, 0x51, 0x03, 0x8c, 0xc0, 0xe7, 0x56, 0x70,
	0x65, 0xa9, 0x77, 0x79, 0xd4, 0x82, 0xa6, 0x8a, 0x6c, 0x9e, 0xc8, 0x6e, 0x05, 0x4a, 0xd8, 0xcf,
	0xdd, 0x03, 0x28, 0x4b, 0x13, 0xda, 0x83, 0xa2, 0xc7, 0xed, 0x2b, 0xac, 0xaa, 0x0d, 0xb5, 0x44,
	0x43, 0xaa, 0xf9, 0xc3, 0x74, 0xf7, 0x09, 0x14, 0xa3, 0xd8, 0xe6, 0x90, 0x48, 0xe2, 0x6e, 0xba,
	0xaf, 0x41, 0x4f, 0xb6, 0x30, 0xed, 0x81, 0xb1, 0x6e, 0xf9, 0xa4, 0xbc, 0x1e, 0x47, 0xf1, 0x39,
	0x1b, 0xe9, 0xab, 0x5f, 0x7b, 0xb9, 0xd5, 0xfd, 0x5e, 0xee, 0xee, 0x7e, 0x2f, 0xe7, 0x94, 0xf1,
	0xbf, 0xe1, 0xf0, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x33, 0x15, 0x80, 0xac, 0x5b, 0x06, 0x00,
	0x00,
}
