// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: objects.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Objects contains examples of nested object and map protobuf field types.
type Objects struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// primitives field.
	Primitives Primitives `protobuf:"bytes,2,opt,name=primitives,proto3" json:"primitives"`
	// string_map map of strings.
	StringMap map[string]string `protobuf:"bytes,3,rep,name=string_map,json=stringMap,proto3" json:"string_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// int_map map of ints.
	IntMap map[string]int64 `protobuf:"bytes,4,rep,name=int_map,json=intMap,proto3" json:"int_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// bool_map map of bools.
	BoolMap map[string]bool `protobuf:"bytes,5,rep,name=bool_map,json=boolMap,proto3" json:"bool_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// nested_value is a nested object.
	NestedValue Nested `protobuf:"bytes,6,opt,name=nested_value,json=nestedValue,proto3" json:"nested_value"`
	// nested_nullable is a nullable nested object.
	NestedNullable *Nested `protobuf:"bytes,7,opt,name=nested_nullable,json=nestedNullable,proto3" json:"nested_nullable,omitempty"`
	// nested_list is a list of nested objects.
	NestedList []Nested `protobuf:"bytes,8,rep,name=nested_list,json=nestedList,proto3" json:"nested_list"`
	// nested_nullable_list is a nullable list of nested objects.
	NestedNullableList []*Nested `protobuf:"bytes,9,rep,name=nested_nullable_list,json=nestedNullableList,proto3" json:"nested_nullable_list,omitempty"`
	// nested_map is a map of nested objects.
	NestedMap map[string]Nested `protobuf:"bytes,10,rep,name=nested_map,json=nestedMap,proto3" json:"nested_map" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// nested_map is a nullable map of nested objects.
	NestedNullableMap map[string]*Nested `protobuf:"bytes,11,rep,name=nested_nullable_map,json=nestedNullableMap,proto3" json:"nested_nullable_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// empty is an empty field.
	Empty *Empty `protobuf:"bytes,12,opt,name=empty,proto3" json:"empty,omitempty"`
	// one_of is a oneof field.
	//
	// Types that are valid to be assigned to OneOf:
	//
	//	*Objects_Branch1
	//	*Objects_Branch2
	OneOf isObjects_OneOf `protobuf_oneof:"one_of"`
	// embeded is an embedded field.
	Nested               `protobuf:"bytes,13,opt,name=embedded,proto3,embedded=embedded" json:"embedded"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Objects) Reset()         { *m = Objects{} }
func (m *Objects) String() string { return proto.CompactTextString(m) }
func (*Objects) ProtoMessage()    {}
func (*Objects) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{0}
}
func (m *Objects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Objects.Unmarshal(m, b)
}
func (m *Objects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Objects.Marshal(b, m, deterministic)
}
func (m *Objects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Objects.Merge(m, src)
}
func (m *Objects) XXX_Size() int {
	return xxx_messageInfo_Objects.Size(m)
}
func (m *Objects) XXX_DiscardUnknown() {
	xxx_messageInfo_Objects.DiscardUnknown(m)
}

var xxx_messageInfo_Objects proto.InternalMessageInfo

type isObjects_OneOf interface {
	isObjects_OneOf()
}

type Objects_Branch1 struct {
	Branch1 *Nested `protobuf:"bytes,15,opt,name=branch1,proto3,oneof" json:"branch1,omitempty"`
}
type Objects_Branch2 struct {
	Branch2 *Nested `protobuf:"bytes,16,opt,name=branch2,proto3,oneof" json:"branch2,omitempty"`
}

func (*Objects_Branch1) isObjects_OneOf() {}
func (*Objects_Branch2) isObjects_OneOf() {}

func (m *Objects) GetOneOf() isObjects_OneOf {
	if m != nil {
		return m.OneOf
	}
	return nil
}

func (m *Objects) GetBranch1() *Nested {
	if x, ok := m.GetOneOf().(*Objects_Branch1); ok {
		return x.Branch1
	}
	return nil
}

func (m *Objects) GetBranch2() *Nested {
	if x, ok := m.GetOneOf().(*Objects_Branch2); ok {
		return x.Branch2
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Objects) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Objects_Branch1)(nil),
		(*Objects_Branch2)(nil),
	}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{1}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Nested struct {
	Leaf                 Leaf     `protobuf:"bytes,1,opt,name=leaf,proto3" json:"leaf"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nested) Reset()         { *m = Nested{} }
func (m *Nested) String() string { return proto.CompactTextString(m) }
func (*Nested) ProtoMessage()    {}
func (*Nested) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{2}
}
func (m *Nested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nested.Unmarshal(m, b)
}
func (m *Nested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nested.Marshal(b, m, deterministic)
}
func (m *Nested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nested.Merge(m, src)
}
func (m *Nested) XXX_Size() int {
	return xxx_messageInfo_Nested.Size(m)
}
func (m *Nested) XXX_DiscardUnknown() {
	xxx_messageInfo_Nested.DiscardUnknown(m)
}

var xxx_messageInfo_Nested proto.InternalMessageInfo

type Leaf struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Leaf) Reset()         { *m = Leaf{} }
func (m *Leaf) String() string { return proto.CompactTextString(m) }
func (*Leaf) ProtoMessage()    {}
func (*Leaf) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{3}
}
func (m *Leaf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Leaf.Unmarshal(m, b)
}
func (m *Leaf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Leaf.Marshal(b, m, deterministic)
}
func (m *Leaf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Leaf.Merge(m, src)
}
func (m *Leaf) XXX_Size() int {
	return xxx_messageInfo_Leaf.Size(m)
}
func (m *Leaf) XXX_DiscardUnknown() {
	xxx_messageInfo_Leaf.DiscardUnknown(m)
}

var xxx_messageInfo_Leaf proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Objects)(nil), "types.Objects")
	proto.RegisterMapType((map[string]bool)(nil), "types.Objects.BoolMapEntry")
	proto.RegisterMapType((map[string]int64)(nil), "types.Objects.IntMapEntry")
	proto.RegisterMapType((map[string]Nested)(nil), "types.Objects.NestedMapEntry")
	proto.RegisterMapType((map[string]*Nested)(nil), "types.Objects.NestedNullableMapEntry")
	proto.RegisterMapType((map[string]string)(nil), "types.Objects.StringMapEntry")
	proto.RegisterType((*Empty)(nil), "types.Empty")
	proto.RegisterType((*Nested)(nil), "types.Nested")
	proto.RegisterType((*Leaf)(nil), "types.Leaf")
}

func init() { proto.RegisterFile("objects.proto", fileDescriptor_7da965bc36916fc1) }

var fileDescriptor_7da965bc36916fc1 = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe3, 0xfc, 0xb3, 0x33, 0x4e, 0xd3, 0x74, 0x89, 0x90, 0x15, 0x20, 0x44, 0x41, 0x95,
	0xc2, 0x25, 0x15, 0x09, 0x2a, 0x50, 0xe5, 0x14, 0x29, 0x12, 0x88, 0x52, 0x90, 0x2b, 0x71, 0xe1,
	0x10, 0xd9, 0xf5, 0x26, 0x18, 0x9c, 0x5d, 0x2b, 0xde, 0x56, 0xca, 0xe3, 0xf0, 0x36, 0x39, 0xf6,
	0x09, 0x90, 0xe8, 0x93, 0x20, 0xcf, 0xae, 0x13, 0xc7, 0x72, 0xe9, 0x81, 0x9b, 0x77, 0xe6, 0xfb,
	0x7d, 0x3b, 0x3b, 0x33, 0x09, 0x1c, 0x70, 0xf7, 0x07, 0xbd, 0x12, 0xd1, 0x20, 0x5c, 0x71, 0xc1,
	0x49, 0x45, 0xac, 0x43, 0x1a, 0xb5, 0x5b, 0x0b, 0xbe, 0xe0, 0x18, 0x39, 0x89, 0xbf, 0x64, 0xb2,
	0xdd, 0x0c, 0x57, 0xfe, 0xd2, 0x17, 0xfe, 0x0d, 0x55, 0xf2, 0xde, 0xaf, 0x1a, 0xe8, 0x9f, 0xa5,
	0x01, 0x69, 0x40, 0xd1, 0xf7, 0x2c, 0xad, 0xab, 0xf5, 0x6b, 0x76, 0xd1, 0xf7, 0xc8, 0x1b, 0x80,
	0x9d, 0xde, 0x2a, 0x76, 0xb5, 0xbe, 0x39, 0x3c, 0x1a, 0xa0, 0xff, 0xe0, 0xcb, 0x36, 0x31, 0x29,
	0x6f, 0x7e, 0x3f, 0x2f, 0xd8, 0x29, 0x29, 0x19, 0x03, 0x44, 0x62, 0xe5, 0xb3, 0xc5, 0x6c, 0xe9,
	0x84, 0x56, 0xa9, 0x5b, 0xea, 0x9b, 0xc3, 0x67, 0x0a, 0x54, 0x97, 0x0d, 0x2e, 0x51, 0xf0, 0xc9,
	0x09, 0xa7, 0x4c, 0xac, 0xd6, 0x76, 0x2d, 0x4a, 0xce, 0x64, 0x04, 0xba, 0xcf, 0x04, 0xa2, 0x65,
	0x44, 0xdb, 0x19, 0xf4, 0x03, 0x13, 0x5b, 0xae, 0xea, 0xe3, 0x81, 0x9c, 0x82, 0xe1, 0x72, 0x1e,
	0x20, 0x55, 0x41, 0xea, 0x49, 0x86, 0x9a, 0x70, 0x1e, 0x6c, 0x31, 0xdd, 0x95, 0x27, 0x72, 0x0a,
	0x75, 0x46, 0x23, 0x41, 0xbd, 0xd9, 0x8d, 0x13, 0x5c, 0x53, 0xab, 0x8a, 0xaf, 0x3c, 0x50, 0xec,
	0x05, 0xa6, 0xd4, 0x0b, 0x4d, 0x29, 0xfc, 0x1a, 0xeb, 0xc8, 0x18, 0x0e, 0x15, 0xc7, 0xae, 0x83,
	0xc0, 0x71, 0x03, 0x6a, 0xe9, 0xf7, 0xa1, 0x9a, 0xdd, 0x90, 0xda, 0x0b, 0x25, 0x25, 0xaf, 0x41,
	0x99, 0xcd, 0x02, 0x3f, 0x12, 0x96, 0x81, 0x05, 0xe7, 0x5e, 0x0a, 0x52, 0x77, 0xee, 0x47, 0x82,
	0x4c, 0xa1, 0x95, 0xb9, 0x53, 0xe2, 0xb5, 0xfb, 0x70, 0xcd, 0x26, 0xfb, 0x17, 0xa3, 0xcd, 0x04,
	0x94, 0x29, 0x36, 0x0b, 0x72, 0xa7, 0x23, 0x4d, 0x92, 0x76, 0xa9, 0x5a, 0x6a, 0x2c, 0x89, 0x92,
	0x6f, 0xf0, 0x28, 0x5b, 0x4a, 0x6c, 0x66, 0xa2, 0xd9, 0x71, 0xae, 0x59, 0x52, 0xc3, 0x9e, 0xa9,
	0x66, 0x1f, 0xb1, 0x6c, 0x96, 0xf4, 0xa0, 0x42, 0x97, 0xa1, 0x58, 0x5b, 0x75, 0xec, 0x68, 0x5d,
	0xd9, 0x4d, 0xe3, 0x98, 0x2d, 0x53, 0xe4, 0x25, 0xe8, 0xee, 0xca, 0x61, 0x57, 0xdf, 0x5f, 0x59,
	0x87, 0x39, 0x7d, 0x7f, 0x5f, 0xb0, 0x93, 0xfc, 0x4e, 0x3a, 0xb4, 0x9a, 0xff, 0x94, 0x0e, 0xc9,
	0x08, 0x0c, 0xba, 0x74, 0xa9, 0xe7, 0x51, 0xcf, 0x3a, 0xc8, 0x1b, 0xa7, 0x11, 0x37, 0xe2, 0x36,
	0xae, 0x7b, 0x2b, 0x6c, 0x8f, 0xa1, 0xb1, 0xbf, 0xcc, 0xa4, 0x09, 0xa5, 0x9f, 0x74, 0xad, 0x7e,
	0x49, 0xf1, 0x27, 0x69, 0x41, 0x45, 0xee, 0x57, 0x11, 0x63, 0xf2, 0x70, 0x56, 0x7c, 0xab, 0xb5,
	0xdf, 0x81, 0x99, 0xda, 0xe7, 0x87, 0xd0, 0x52, 0x1a, 0x3d, 0x83, 0x7a, 0x7a, 0xa9, 0x1f, 0x62,
	0x8d, 0x34, 0xfb, 0x11, 0x1a, 0xfb, 0x33, 0xce, 0xa1, 0x5f, 0xa4, 0xe9, 0x6c, 0x2b, 0xd2, 0x66,
	0x97, 0xf0, 0x38, 0x7f, 0xc6, 0xff, 0x61, 0x3a, 0x31, 0xa0, 0xca, 0x19, 0x9d, 0xf1, 0x79, 0x4f,
	0x87, 0x0a, 0xce, 0xbe, 0x77, 0x02, 0x55, 0xa9, 0x23, 0xc7, 0x50, 0x0e, 0xa8, 0x33, 0x47, 0x63,
	0x73, 0x68, 0x2a, 0x93, 0x73, 0xea, 0xcc, 0xd5, 0xae, 0x62, 0xba, 0xf7, 0x14, 0xca, 0x71, 0x6c,
	0xd7, 0x07, 0x2d, 0xd5, 0xfe, 0x49, 0x7d, 0xf3, 0xa7, 0x53, 0xd8, 0xdc, 0x75, 0x0a, 0xb7, 0x77,
	0x9d, 0x82, 0x5b, 0xc5, 0x3f, 0xc4, 0xd1, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0xeb, 0xd4,
	0x33, 0x50, 0x05, 0x00, 0x00,
}
