// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: primitives.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EnumValue is an enum field.
type EnumValue int32

const (
	EnumValue_ENUM_UNSPECIFIED EnumValue = 0
	EnumValue_ENUM_VALUE_ONE   EnumValue = 1
	EnumValue_ENUM_VALUE_TWO   EnumValue = 2
)

var EnumValue_name = map[int32]string{
	0: "ENUM_UNSPECIFIED",
	1: "ENUM_VALUE_ONE",
	2: "ENUM_VALUE_TWO",
}

var EnumValue_value = map[string]int32{
	"ENUM_UNSPECIFIED": 0,
	"ENUM_VALUE_ONE":   1,
	"ENUM_VALUE_TWO":   2,
}

func (x EnumValue) String() string {
	return proto.EnumName(EnumValue_name, int32(x))
}

func (EnumValue) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_060c1ac18e7b73a6, []int{0}
}

// BoolValue wraps a bool so it can be used as a nullable message field.
type BoolValue struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolValue) Reset()         { *m = BoolValue{} }
func (m *BoolValue) String() string { return proto.CompactTextString(m) }
func (*BoolValue) ProtoMessage()    {}
func (*BoolValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_060c1ac18e7b73a6, []int{0}
}
func (m *BoolValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolValue.Unmarshal(m, b)
}
func (m *BoolValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolValue.Marshal(b, m, deterministic)
}
func (m *BoolValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolValue.Merge(m, src)
}
func (m *BoolValue) XXX_Size() int {
	return xxx_messageInfo_BoolValue.Size(m)
}
func (m *BoolValue) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolValue.DiscardUnknown(m)
}

var xxx_messageInfo_BoolValue proto.InternalMessageInfo

// Primitives contains primitive/scalar protobuf field types and list variants.
type Primitives struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// string_value string field.
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	// int32_value int32 field.
	Int32Value int32 `protobuf:"varint,3,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	// int64_value int64 field.
	Int64Value int64 `protobuf:"varint,4,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	// float_value float32 field.
	FloatValue float32 `protobuf:"fixed32,5,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	// double_value float64 field.
	DoubleValue float64 `protobuf:"fixed64,6,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	// bool_value bool field.
	BoolValue bool `protobuf:"varint,7,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	// bytes_value bytes field.
	BytesValue []byte `protobuf:"bytes,8,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	// enum_value enum field.
	EnumValue EnumValue `protobuf:"varint,9,opt,name=enum_value,json=enumValue,proto3,enum=types.EnumValue" json:"enum_value,omitempty"`
	// nullable_value is a message rather than primitive field so it can be set to
	// null in the config. Tests verify that null/not-null status is preserved.
	NullableValue *BoolValue `protobuf:"bytes,10,opt,name=nullable_value,json=nullableValue,proto3" json:"nullable_value,omitempty"`
	// optional_string non-nullable because it's a primitive, but it will be set
	// as optional in the Terraform config, and therefore must also be set as
	// computed. The provider will return the string zero value ("") and tests
	// will verify both that value and that it's not marked as null in Terraform.
	OptionalString string `protobuf:"bytes,19,opt,name=optional_string,json=optionalString,proto3" json:"optional_string,omitempty"`
	// string_list string list field.
	StringList []string `protobuf:"bytes,11,rep,name=string_list,json=stringList,proto3" json:"string_list,omitempty"`
	// int32_list int32 list field.
	Int32List []int32 `protobuf:"varint,12,rep,packed,name=int32_list,json=int32List,proto3" json:"int32_list,omitempty"`
	// int64_list int64 list field.
	Int64List []int64 `protobuf:"varint,13,rep,packed,name=int64_list,json=int64List,proto3" json:"int64_list,omitempty"`
	// float_list float list field.
	FloatList []float32 `protobuf:"fixed32,14,rep,packed,name=float_list,json=floatList,proto3" json:"float_list,omitempty"`
	// double_list double list field.
	DoubleList []float64 `protobuf:"fixed64,15,rep,packed,name=double_list,json=doubleList,proto3" json:"double_list,omitempty"`
	// bool_list bool list field.
	BoolList []bool `protobuf:"varint,16,rep,packed,name=bool_list,json=boolList,proto3" json:"bool_list,omitempty"`
	// bytes_list bytes list field.
	BytesList [][]byte `protobuf:"bytes,17,rep,name=bytes_list,json=bytesList,proto3" json:"bytes_list,omitempty"`
	// enum_list enum list field.
	EnumList             []EnumValue `protobuf:"varint,18,rep,packed,name=enum_list,json=enumList,proto3,enum=types.EnumValue" json:"enum_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Primitives) Reset()         { *m = Primitives{} }
func (m *Primitives) String() string { return proto.CompactTextString(m) }
func (*Primitives) ProtoMessage()    {}
func (*Primitives) Descriptor() ([]byte, []int) {
	return fileDescriptor_060c1ac18e7b73a6, []int{1}
}
func (m *Primitives) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Primitives.Unmarshal(m, b)
}
func (m *Primitives) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Primitives.Marshal(b, m, deterministic)
}
func (m *Primitives) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Primitives.Merge(m, src)
}
func (m *Primitives) XXX_Size() int {
	return xxx_messageInfo_Primitives.Size(m)
}
func (m *Primitives) XXX_DiscardUnknown() {
	xxx_messageInfo_Primitives.DiscardUnknown(m)
}

var xxx_messageInfo_Primitives proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("types.EnumValue", EnumValue_name, EnumValue_value)
	proto.RegisterType((*BoolValue)(nil), "types.BoolValue")
	proto.RegisterType((*Primitives)(nil), "types.Primitives")
}

func init() { proto.RegisterFile("primitives.proto", fileDescriptor_060c1ac18e7b73a6) }

var fileDescriptor_060c1ac18e7b73a6 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0x86, 0xbd, 0xda, 0x28, 0xb5, 0x46, 0x8a, 0xa2, 0xaa, 0x3e, 0x98, 0x96, 0xda, 0xeb, 0x5c,
	0xba, 0x14, 0xea, 0x40, 0x62, 0x7c, 0xeb, 0xa1, 0x6e, 0x55, 0x30, 0xa4, 0x4e, 0xd8, 0xd4, 0xe9,
	0xd1, 0xd8, 0x58, 0x35, 0x0b, 0xb2, 0xd6, 0x58, 0xeb, 0x40, 0xde, 0xa8, 0x8f, 0xe2, 0x63, 0x9f,
	0xa0, 0xd0, 0x3c, 0x49, 0xd1, 0x8c, 0xac, 0x86, 0xd2, 0xdb, 0xfa, 0xfb, 0xbf, 0x1d, 0x76, 0x7e,
	0x23, 0x88, 0x36, 0x5b, 0xbd, 0xd6, 0x56, 0xdf, 0xa7, 0x45, 0x7f, 0xb3, 0x35, 0xd6, 0xc4, 0xae,
	0x7d, 0xd8, 0xa4, 0xc5, 0xcb, 0xd6, 0xca, 0xac, 0x0c, 0x92, 0xf3, 0xf2, 0x44, 0xe1, 0x59, 0x0f,
	0xbc, 0x91, 0x31, 0xd9, 0xdd, 0x3c, 0xdb, 0xa5, 0x71, 0x0b, 0xdc, 0xfb, 0xf2, 0xd0, 0x66, 0x82,
	0xc9, 0xa6, 0xa2, 0x1f, 0x67, 0x3f, 0x5c, 0x80, 0x9b, 0x7a, 0x68, 0x1c, 0x82, 0xa3, 0x97, 0x68,
	0x78, 0xca, 0xd1, 0xcb, 0xb8, 0x07, 0x41, 0x61, 0xb7, 0x3a, 0x5f, 0xcd, 0xe8, 0xae, 0x83, 0x89,
	0x4f, 0x8c, 0xe6, 0x76, 0xc1, 0xd7, 0xb9, 0xbd, 0xbc, 0xa8, 0x0c, 0x2e, 0x98, 0x74, 0x15, 0x20,
	0x7a, 0x2a, 0x0c, 0x07, 0x95, 0x70, 0x24, 0x98, 0xe4, 0x28, 0x0c, 0x07, 0xb5, 0xf0, 0x3d, 0x33,
	0x73, 0x5b, 0x09, 0xae, 0x60, 0xd2, 0x51, 0x80, 0x88, 0x84, 0x1e, 0x04, 0x4b, 0xb3, 0x5b, 0x64,
	0x69, 0x65, 0x1c, 0x0b, 0x26, 0x99, 0xf2, 0x89, 0x91, 0xf2, 0x1a, 0x60, 0x61, 0x4c, 0x56, 0x09,
	0xcf, 0x70, 0x45, 0x6f, 0x51, 0x2f, 0xdf, 0x05, 0x7f, 0xf1, 0x60, 0xd3, 0xa2, 0xca, 0x9b, 0x82,
	0xc9, 0x40, 0x01, 0x22, 0x12, 0xce, 0x01, 0xd2, 0x7c, 0xb7, 0xae, 0x72, 0x4f, 0x30, 0x19, 0x5e,
	0x44, 0x7d, 0x2c, 0xb7, 0x9f, 0xe4, 0xbb, 0x35, 0x5a, 0xca, 0x4b, 0x0f, 0xc7, 0xf8, 0x3d, 0x84,
	0xf9, 0x2e, 0xcb, 0xe6, 0x7f, 0x5f, 0x05, 0x82, 0x49, 0xbf, 0xbe, 0x54, 0x17, 0x3f, 0x3a, 0xda,
	0xff, 0xea, 0x32, 0x75, 0x72, 0xb0, 0xe9, 0xfa, 0x1b, 0x38, 0x35, 0x1b, 0xab, 0x4d, 0x3e, 0xcf,
	0x66, 0xd4, 0x66, 0xfb, 0x05, 0x76, 0x1b, 0x1e, 0xf0, 0x2d, 0xd2, 0xf2, 0xe5, 0xd5, 0x3f, 0x90,
	0xe9, 0xc2, 0xb6, 0x7d, 0xc1, 0xa5, 0xa7, 0x80, 0xd0, 0x95, 0x2e, 0x6c, 0xb9, 0x39, 0xf5, 0x8f,
	0x79, 0x20, 0xb8, 0x74, 0x95, 0x87, 0xe4, 0x49, 0x3c, 0x1c, 0x50, 0x7c, 0x22, 0xb8, 0xe4, 0x18,
	0x0f, 0x07, 0x87, 0x98, 0xba, 0xc7, 0x38, 0x14, 0x5c, 0x3a, 0xca, 0x43, 0x82, 0x71, 0x17, 0xaa,
	0x96, 0x29, 0x3f, 0x15, 0x5c, 0x32, 0x05, 0x84, 0x50, 0x78, 0x05, 0xd8, 0x32, 0xc5, 0x91, 0xe0,
	0xb2, 0xa9, 0x9a, 0x25, 0x38, 0x0c, 0xa7, 0xd6, 0x31, 0x7d, 0x2e, 0xb8, 0x0c, 0x94, 0x87, 0x04,
	0xe3, 0x77, 0x80, 0x7d, 0x52, 0x1a, 0x0b, 0xfe, 0xdf, 0xca, 0x9b, 0xa5, 0x52, 0xea, 0x6f, 0xc7,
	0xe0, 0xd5, 0x38, 0x6e, 0x41, 0x94, 0x4c, 0xa6, 0x5f, 0x66, 0xd3, 0xc9, 0xed, 0x4d, 0xf2, 0x71,
	0xfc, 0x79, 0x9c, 0x7c, 0x8a, 0x1a, 0x71, 0x0c, 0x21, 0xd2, 0xbb, 0x0f, 0x57, 0xd3, 0x64, 0x76,
	0x3d, 0x49, 0x22, 0xf6, 0x0f, 0xfb, 0xfa, 0xed, 0x3a, 0x72, 0x46, 0xc1, 0xfe, 0x77, 0xa7, 0xb1,
	0x7f, 0xec, 0x34, 0x7e, 0x3e, 0x76, 0x1a, 0x8b, 0x63, 0xfc, 0x5a, 0x2e, 0xff, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x83, 0x8a, 0xd8, 0x7b, 0x5e, 0x03, 0x00, 0x00,
}
