/*
Copyright 2015-2022 Gravitational, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: time.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"
	time "time"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gravitational_protoc_gen_terraform_v3_examples_types "github.com/gravitational/protoc-gen-terraform/v3/examples/types"
	github_com_hashicorp_terraform_plugin_framework_attr "github.com/hashicorp/terraform-plugin-framework/attr"
	github_com_hashicorp_terraform_plugin_framework_diag "github.com/hashicorp/terraform-plugin-framework/diag"
	github_com_hashicorp_terraform_plugin_framework_tfsdk "github.com/hashicorp/terraform-plugin-framework/tfsdk"
	github_com_hashicorp_terraform_plugin_framework_types "github.com/hashicorp/terraform-plugin-framework/types"
	github_com_hashicorp_terraform_plugin_go_tftypes "github.com/hashicorp/terraform-plugin-go/tftypes"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// GenSchemaTime returns tfsdk.Schema definition for Time
func GenSchemaTime(ctx context.Context) (github_com_hashicorp_terraform_plugin_framework_tfsdk.Schema, github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics) {
	return github_com_hashicorp_terraform_plugin_framework_tfsdk.Schema{Attributes: map[string]github_com_hashicorp_terraform_plugin_framework_tfsdk.Attribute{
		"duration_custom": {
			Description: "duration_custom time.Duration field using casttype.",
			Optional:    true,
			Type:        DurationType{},
		},
		"duration_custom_list": {
			Description: "duration_custom_list []time.Duration field using casttype.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.ListType{ElemType: DurationType{}},
		},
		"duration_list": {
			Description: "duration_list []time.Duration field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.ListType{ElemType: DurationType{}},
		},
		"duration_standard": {
			Description: "duration_standard time.Duration field using stdduration.",
			Optional:    true,
			Type:        DurationType{},
		},
		"id": {
			Computed:      true,
			Description:   "",
			Optional:      true,
			PlanModifiers: []github_com_hashicorp_terraform_plugin_framework_tfsdk.AttributePlanModifier{github_com_hashicorp_terraform_plugin_framework_tfsdk.UseStateForUnknown()},
			Type:          github_com_hashicorp_terraform_plugin_framework_types.StringType,
		},
		"timestamp_list": {
			Description: "timestamp_list []time.Time field.",
			Optional:    true,
			Type:        github_com_hashicorp_terraform_plugin_framework_types.ListType{ElemType: UseRFC3339Time()},
		},
		"timestamp_value": {
			Description: "timestamp_value time.Time field.",
			Optional:    true,
			Type:        UseRFC3339Time(),
		},
	}}, nil
}

// CopyTimeFromTerraform copies contents of the source Terraform object into a target struct
func CopyTimeFromTerraform(_ context.Context, tf github_com_hashicorp_terraform_plugin_framework_types.Object, obj *github_com_gravitational_protoc_gen_terraform_v3_examples_types.Time) github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics {
	var diags github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics
	{
		a, ok := tf.Attrs["duration_custom"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Time.duration_custom"})
		} else {
			v, ok := a.(DurationValue)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Time.duration_custom", "DurationValue"})
			} else {
				var t github_com_gravitational_protoc_gen_terraform_v3_examples_types.Duration
				if !v.Null && !v.Unknown {
					t = github_com_gravitational_protoc_gen_terraform_v3_examples_types.Duration(v.Value)
				}
				obj.DurationCustom = t
			}
		}
	}
	{
		a, ok := tf.Attrs["duration_custom_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Time.duration_custom_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Time.duration_custom_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.DurationCustomList = make([]github_com_gravitational_protoc_gen_terraform_v3_examples_types.Duration, len(v.Elems))
				if !v.Null && !v.Unknown {
					for k, a := range v.Elems {
						v, ok := a.(DurationValue)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Time.duration_custom_list", "DurationValue"})
						} else {
							var t github_com_gravitational_protoc_gen_terraform_v3_examples_types.Duration
							if !v.Null && !v.Unknown {
								t = github_com_gravitational_protoc_gen_terraform_v3_examples_types.Duration(v.Value)
							}
							obj.DurationCustomList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["duration_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Time.duration_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Time.duration_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.DurationList = make([]time.Duration, len(v.Elems))
				if !v.Null && !v.Unknown {
					for k, a := range v.Elems {
						v, ok := a.(DurationValue)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Time.duration_list", "DurationValue"})
						} else {
							var t time.Duration
							if !v.Null && !v.Unknown {
								t = time.Duration(v.Value)
							}
							obj.DurationList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["duration_standard"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Time.duration_standard"})
		} else {
			v, ok := a.(DurationValue)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Time.duration_standard", "DurationValue"})
			} else {
				var t time.Duration
				if !v.Null && !v.Unknown {
					t = time.Duration(v.Value)
				}
				obj.DurationStandard = t
			}
		}
	}
	{
		a, ok := tf.Attrs["id"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Time.id"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Time.id", "github.com/hashicorp/terraform-plugin-framework/types.String"})
			} else {
				var t string
				if !v.Null && !v.Unknown {
					t = string(v.Value)
				}
				obj.Id = t
			}
		}
	}
	{
		a, ok := tf.Attrs["timestamp_list"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Time.timestamp_list"})
		} else {
			v, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.List)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Time.timestamp_list", "github.com/hashicorp/terraform-plugin-framework/types.List"})
			} else {
				obj.TimestampList = make([]time.Time, len(v.Elems))
				if !v.Null && !v.Unknown {
					for k, a := range v.Elems {
						v, ok := a.(TimeValue)
						if !ok {
							diags.Append(attrReadConversionFailureDiag{"Time.timestamp_list", "TimeValue"})
						} else {
							var t time.Time
							if !v.Null && !v.Unknown {
								t = time.Time(v.Value)
							}
							obj.TimestampList[k] = t
						}
					}
				}
			}
		}
	}
	{
		a, ok := tf.Attrs["timestamp_value"]
		if !ok {
			diags.Append(attrReadMissingDiag{"Time.timestamp_value"})
		} else {
			v, ok := a.(TimeValue)
			if !ok {
				diags.Append(attrReadConversionFailureDiag{"Time.timestamp_value", "TimeValue"})
			} else {
				var t time.Time
				if !v.Null && !v.Unknown {
					t = time.Time(v.Value)
				}
				obj.TimestampValue = t
			}
		}
	}
	return diags
}

// CopyTimeToTerraform copies contents of the source Terraform object into a target struct
func CopyTimeToTerraform(ctx context.Context, obj *github_com_gravitational_protoc_gen_terraform_v3_examples_types.Time, tf *github_com_hashicorp_terraform_plugin_framework_types.Object) github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics {
	var diags github_com_hashicorp_terraform_plugin_framework_diag.Diagnostics
	tf.Null = false
	tf.Unknown = false
	if tf.Attrs == nil {
		tf.Attrs = make(map[string]github_com_hashicorp_terraform_plugin_framework_attr.Value)
	}
	{
		t, ok := tf.AttrTypes["duration_custom"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Time.duration_custom"})
		} else {
			v, ok := tf.Attrs["duration_custom"].(DurationValue)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Time.duration_custom", err})
				}
				v, ok = i.(DurationValue)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Time.duration_custom", "DurationValue"})
				}
				v.Null = false
			}
			v.Value = time.Duration(obj.DurationCustom)
			v.Unknown = false
			tf.Attrs["duration_custom"] = v
		}
	}
	{
		a, ok := tf.AttrTypes["duration_custom_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Time.duration_custom_list"})
		} else {
			o, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Time.duration_custom_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				c, ok := tf.Attrs["duration_custom_list"].(github_com_hashicorp_terraform_plugin_framework_types.List)
				if !ok {
					c = github_com_hashicorp_terraform_plugin_framework_types.List{

						ElemType: o.ElemType,
						Elems:    make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.DurationCustomList)),
						Null:     true,
					}
				} else {
					if c.Elems == nil {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.DurationCustomList))
					}
				}
				if obj.DurationCustomList != nil {
					t := o.ElemType
					if len(obj.DurationCustomList) != len(c.Elems) {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.DurationCustomList))
					}
					for k, a := range obj.DurationCustomList {
						v, ok := c.Elems[k].(DurationValue)
						if !ok {
							i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
							if err != nil {
								diags.Append(attrWriteGeneralError{"Time.duration_custom_list", err})
							}
							v, ok = i.(DurationValue)
							if !ok {
								diags.Append(attrWriteConversionFailureDiag{"Time.duration_custom_list", "DurationValue"})
							}
							v.Null = false
						}
						v.Value = time.Duration(a)
						v.Unknown = false
						c.Elems[k] = v
					}
					if len(obj.DurationCustomList) > 0 {
						c.Null = false
					}
				}
				c.Unknown = false
				tf.Attrs["duration_custom_list"] = c
			}
		}
	}
	{
		a, ok := tf.AttrTypes["duration_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Time.duration_list"})
		} else {
			o, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Time.duration_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				c, ok := tf.Attrs["duration_list"].(github_com_hashicorp_terraform_plugin_framework_types.List)
				if !ok {
					c = github_com_hashicorp_terraform_plugin_framework_types.List{

						ElemType: o.ElemType,
						Elems:    make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.DurationList)),
						Null:     true,
					}
				} else {
					if c.Elems == nil {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.DurationList))
					}
				}
				if obj.DurationList != nil {
					t := o.ElemType
					if len(obj.DurationList) != len(c.Elems) {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.DurationList))
					}
					for k, a := range obj.DurationList {
						v, ok := c.Elems[k].(DurationValue)
						if !ok {
							i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
							if err != nil {
								diags.Append(attrWriteGeneralError{"Time.duration_list", err})
							}
							v, ok = i.(DurationValue)
							if !ok {
								diags.Append(attrWriteConversionFailureDiag{"Time.duration_list", "DurationValue"})
							}
							v.Null = false
						}
						v.Value = time.Duration(a)
						v.Unknown = false
						c.Elems[k] = v
					}
					if len(obj.DurationList) > 0 {
						c.Null = false
					}
				}
				c.Unknown = false
				tf.Attrs["duration_list"] = c
			}
		}
	}
	{
		t, ok := tf.AttrTypes["duration_standard"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Time.duration_standard"})
		} else {
			v, ok := tf.Attrs["duration_standard"].(DurationValue)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Time.duration_standard", err})
				}
				v, ok = i.(DurationValue)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Time.duration_standard", "DurationValue"})
				}
				v.Null = false
			}
			v.Value = time.Duration(obj.DurationStandard)
			v.Unknown = false
			tf.Attrs["duration_standard"] = v
		}
	}
	{
		t, ok := tf.AttrTypes["id"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Time.id"})
		} else {
			v, ok := tf.Attrs["id"].(github_com_hashicorp_terraform_plugin_framework_types.String)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Time.id", err})
				}
				v, ok = i.(github_com_hashicorp_terraform_plugin_framework_types.String)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Time.id", "github.com/hashicorp/terraform-plugin-framework/types.String"})
				}
				v.Null = false
			}
			v.Value = string(obj.Id)
			v.Unknown = false
			tf.Attrs["id"] = v
		}
	}
	{
		a, ok := tf.AttrTypes["timestamp_list"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Time.timestamp_list"})
		} else {
			o, ok := a.(github_com_hashicorp_terraform_plugin_framework_types.ListType)
			if !ok {
				diags.Append(attrWriteConversionFailureDiag{"Time.timestamp_list", "github.com/hashicorp/terraform-plugin-framework/types.ListType"})
			} else {
				c, ok := tf.Attrs["timestamp_list"].(github_com_hashicorp_terraform_plugin_framework_types.List)
				if !ok {
					c = github_com_hashicorp_terraform_plugin_framework_types.List{

						ElemType: o.ElemType,
						Elems:    make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.TimestampList)),
						Null:     true,
					}
				} else {
					if c.Elems == nil {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.TimestampList))
					}
				}
				if obj.TimestampList != nil {
					t := o.ElemType
					if len(obj.TimestampList) != len(c.Elems) {
						c.Elems = make([]github_com_hashicorp_terraform_plugin_framework_attr.Value, len(obj.TimestampList))
					}
					for k, a := range obj.TimestampList {
						v, ok := c.Elems[k].(TimeValue)
						if !ok {
							i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
							if err != nil {
								diags.Append(attrWriteGeneralError{"Time.timestamp_list", err})
							}
							v, ok = i.(TimeValue)
							if !ok {
								diags.Append(attrWriteConversionFailureDiag{"Time.timestamp_list", "TimeValue"})
							}
							v.Null = false
						}
						v.Value = time.Time(a)
						v.Unknown = false
						c.Elems[k] = v
					}
					if len(obj.TimestampList) > 0 {
						c.Null = false
					}
				}
				c.Unknown = false
				tf.Attrs["timestamp_list"] = c
			}
		}
	}
	{
		t, ok := tf.AttrTypes["timestamp_value"]
		if !ok {
			diags.Append(attrWriteMissingDiag{"Time.timestamp_value"})
		} else {
			v, ok := tf.Attrs["timestamp_value"].(TimeValue)
			if !ok {
				i, err := t.ValueFromTerraform(ctx, github_com_hashicorp_terraform_plugin_go_tftypes.NewValue(t.TerraformType(ctx), nil))
				if err != nil {
					diags.Append(attrWriteGeneralError{"Time.timestamp_value", err})
				}
				v, ok = i.(TimeValue)
				if !ok {
					diags.Append(attrWriteConversionFailureDiag{"Time.timestamp_value", "TimeValue"})
				}
				v.Null = false
			}
			v.Value = time.Time(obj.TimestampValue)
			v.Unknown = false
			tf.Attrs["timestamp_value"] = v
		}
	}
	return diags
}

// attrReadMissingDiag represents diagnostic message on an attribute missing in the source object
type attrReadMissingDiag struct {
	Path string
}

func (d attrReadMissingDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrReadMissingDiag) Summary() string {
	return "Error reading from Terraform object"
}

func (d attrReadMissingDiag) Detail() string {
	return fmt.Sprintf("A value for %v is missing in the source Terraform object Attrs", d.Path)
}

func (d attrReadMissingDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrReadConversionFailureDiag represents diagnostic message on a failed type conversion on read
type attrReadConversionFailureDiag struct {
	Path string
	Type string
}

func (d attrReadConversionFailureDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrReadConversionFailureDiag) Summary() string {
	return "Error reading from Terraform object"
}

func (d attrReadConversionFailureDiag) Detail() string {
	return fmt.Sprintf("A value for %v can not be converted to %v", d.Path, d.Type)
}

func (d attrReadConversionFailureDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteMissingDiag represents diagnostic message on an attribute missing in the target object
type attrWriteMissingDiag struct {
	Path string
}

func (d attrWriteMissingDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteMissingDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteMissingDiag) Detail() string {
	return fmt.Sprintf("A value for %v is missing in the source Terraform object AttrTypes", d.Path)
}

func (d attrWriteMissingDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteConversionFailureDiag represents diagnostic message on a failed type conversion on write
type attrWriteConversionFailureDiag struct {
	Path string
	Type string
}

func (d attrWriteConversionFailureDiag) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteConversionFailureDiag) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteConversionFailureDiag) Detail() string {
	return fmt.Sprintf("A value for %v can not be converted to %v", d.Path, d.Type)
}

func (d attrWriteConversionFailureDiag) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}

// attrWriteGeneralError represents diagnostic message on a generic error on write
type attrWriteGeneralError struct {
	Path string
	Err  error
}

func (d attrWriteGeneralError) Severity() github_com_hashicorp_terraform_plugin_framework_diag.Severity {
	return github_com_hashicorp_terraform_plugin_framework_diag.SeverityError
}

func (d attrWriteGeneralError) Summary() string {
	return "Error writing to Terraform object"
}

func (d attrWriteGeneralError) Detail() string {
	return fmt.Sprintf("%s: %s", d.Path, d.Err.Error())
}

func (d attrWriteGeneralError) Equal(o github_com_hashicorp_terraform_plugin_framework_diag.Diagnostic) bool {
	return (d.Severity() == o.Severity()) && (d.Summary() == o.Summary()) && (d.Detail() == o.Detail())
}
