name: Go

on:
  - push
  - pull_request

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Install Protoc
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

    - name: Install protoc-gen-gogo
      run: go install github.com/gogo/protobuf/protoc-gen-gogo@v1.3.2

    - name: Install protoc-gen-go
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.6
        terraform_wrapper: false

    - name: Export Terraform path
      run: echo "TF_ACC_TERRAFORM_PATH=$(command -v terraform)" >> "$GITHUB_ENV"

    - name: Build
      run: make build

    - name: Test
      run: make test
